name = "digitaltwin"
main = "worker.js"
compatibility_date = "2026-09-20"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://juldigi.github.io,https://juldigi0107.github.io"

[assets]
directory = "../dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
