import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {DIANA_EYE55_SPEC} from './data/dimensions-diana-eye55.js';import {DIANA_EYE55_TAXONOMY,DIANA_EYE55_TAXONOMY_BY_ID} from './data/taxonomy-diana-eye55.js';import {DIANA_EYE55_ORIENTATION,DIANA_EYE55_TECHNICAL_SOURCES} from './data/sources-diana-eye55.js';import {V141_SOURCE_STATS} from './data/research-v141.js';
const V=a=>new THREE.Vector3(...a);
export class DianaEye55MachineTemplate{
 constructor(){this.spec=DIANA_EYE55_SPEC;this.root=new THREE.Group();this.root.name='IPM 3 · DIANA EYE 55';this.root.userData={assetId:this.spec.assetId,nodeId:'diana55-root',spec:this.spec,sources:DIANA_EYE55_TECHNICAL_SOURCES,orientation:DIANA_EYE55_ORIENTATION,taxonomyVersion:'diana55-v3-trigger-reject-interlock',detailPass:'V141_DIANA55_TRIGGER_CAPTURE_DECISION_EJECTION',evidenceGrade:'OEM_PROCESS_GROUNDED',geometryStatus:'OEM_CAPABILITY_REFERENCE__INSTALLED_CAMERA_REJECT_OPTIONS_BOUNDED',engineeringDimensions:false};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.enrichV141();this.taxonomy=DIANA_EYE55_TAXONOMY;this.taxonomyById=DIANA_EYE55_TAXONOMY_BY_ID;for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'OEM_PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={white:0xebeeee,light:0xcbd0d2,dark:0x252b2f,black:0x0d1215,steel:0x8a969b,silver:0xc3cacc,rubber:0x23282a,red:0xb4312e,blue:0x3c7289,green:0x579071,amber:0xd29b43,paper:0xe1cca2,glass:0x365c67,led:0xf0e7c2}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.5:.08,roughness:k==='glass'?.16:.43,transparent:k==='glass',opacity:k==='glass'?.42:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,22),'c'+r+l+axis,k,p,rot);
  const rotating=/^(feed-pulley|transport-pulley|vacuum-blower|delivery-pulley)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;
  if(rotating)m.userData.spinDirection=/^(transport-pulley|delivery-pulley)$/.test(role)?-1:1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildAccess();this.buildFeeder();this.buildTransport();this.buildInspection();this.buildCameras();this.buildLights();this.buildProcessing();this.buildReject();this.buildDelivery();this.buildExteriorIdentity();}
 buildAccess(){const g=this.group(this.root,'diana55-access','Frame and guarding');const frame=this.group(g,'diana55-access-frame','Machine base and side frames');this.box(frame,[7.90,.28,1.75],[.05,.20,0],'light',.04);for(let x=-3.65;x<=3.70;x+=.85)for(const z of [-.75,.75])this.box(frame,[.08,.58,.08],[x,.53,z],'steel',.012);const guard=this.group(g,'diana55-access-guard','Inspection guards and panels');for(const z of [-.88,.88]){this.cover(this.box(guard,[2.12,1.86,.08],[-.20,1.47,z],'white',.06));this.cover(this.box(guard,[1.18,1.18,.08],[1.70,1.13,z],'white',.05));}const door=this.group(g,'diana55-access-door','Service-access panels');for(const x of [-.72,.28])this.cover(this.box(door,[.74,.76,.025],[x,1.17,-.935],'light',.025));}
 buildFeeder(){const g=this.group(this.root,'diana55-feeder','Blank feeding and alignment',[-3.40,0,0],[-.68,.16,0]);const stack=this.group(g,'diana55-feed-stack','Blank stack support');this.box(stack,[.82,.08,1.18],[-.36,.38,0],'steel');for(let i=0;i<12;i++)this.box(stack,[.54,.012,.80],[-.44,.47+i*.013,0],'paper',.002);const friction=this.group(g,'diana55-feed-friction','Friction feeder belts');for(const z of [-.45,-.15,.15,.45]){this.box(friction,[1.12,.025,.10],[.20,.78,z],'rubber',.006);this.cyl(friction,.055,.15,[.65,.77,z],'rubber','feed-pulley','z');}const align=this.group(g,'diana55-feed-align','Blank aligning guides');for(const z of [-.58,.58])this.box(align,[1.14,.06,.04],[.30,1.02,z],'steel',.008);const dbl=this.group(g,'diana55-feed-double','Double-sheet sensing zone');for(const z of [-.38,.38])this.box(dbl,[.08,.18,.10],[.66,1.05,z],'blue',.018);}
 buildTransport(){const g=this.group(this.root,'diana55-transport','Suction-belt transport',[-1.95,0,0],[-.30,.16,0]);const belt=this.group(g,'diana55-transport-belt','Suction belt');for(const z of [-.50,-.25,0,.25,.50]){const b=this.box(belt,[2.25,.025,.105],[0,.78,z],'rubber',.006);b.userData.suctionBelt=true;for(const x of [-.95,.95])this.cyl(belt,.055,.15,[x,.77,z],'steel','transport-pulley','z');}
 const drive=this.group(g,'diana55-transport-drive','Suction-belt drive / encoder reference');const motor=this.cyl(drive,.10,.24,[-.84,.49,.69],'dark','transport-drive-motor','x');motor.userData.rotor=true;motor.userData.rotorAxis='x';motor.userData.spinDirection=1;const coupling=this.cyl(drive,.045,.10,[-.68,.49,.69],'red','transport-drive-coupling','x');coupling.userData.mechanismRole='transport-drive-coupling';const enc=this.cyl(drive,.055,.026,[.86,.77,.69],'blue','transport-encoder','z');enc.userData.rotor=true;enc.userData.rotorAxis='z';enc.userData.spinDirection=-1;
 const vac=this.group(g,'diana55-transport-vacuum','Vacuum plenum');this.box(vac,[2.12,.34,1.22],[0,.55,0],'dark',.03);for(const x of [-.70,0,.70])this.cyl(vac,.055,.55,[x,.42,.68],'blue','vacuum-blower','x');const vg=this.cyl(vac,.055,.025,[.83,.60,.68],'glass','vacuum-pressure-gauge','z');vg.userData.mechanismRole='vacuum-pressure-gauge';
 const trigger=this.group(g,'diana55-transport-trigger','Inspection trigger / blank presence sensing');for(const z of [-.38,.38]){const p=this.box(trigger,[.045,.075,.045],[.88,.96,z],z<0?'blue':'green',.005);p.userData.mechanismRole=z<0?'inspection-trigger-emitter':'inspection-trigger-receiver';}
 const guide=this.group(g,'diana55-transport-guide','Transport guide rails');for(const z of [-.62,.62])this.box(guide,[2.18,.055,.045],[0,1.02,z],'steel',.008);}
 buildInspection(){const g=this.group(this.root,'diana55-inspection','Inspection enclosure',[-.15,0,0],[0,.30,.42]);const tunnel=this.group(g,'diana55-inspection-tunnel','Inspection tunnel / enclosure');this.cover(this.box(tunnel,[2.18,2.05,1.78],[0,1.48,0],'white',.08));const window=this.group(g,'diana55-inspection-window','Darkened inspection window');for(const z of [-.91,.91])this.box(window,[1.42,.86,.025],[0,1.54,z],'glass',.04);const bed=this.group(g,'diana55-inspection-bed','Inspection belt bed');for(const z of [-.50,-.25,0,.25,.50]){const b=this.box(bed,[2.12,.025,.105],[0,.79,z],'rubber',.005);b.userData.inspectBelt=true;}}
 buildCameras(){const g=this.group(this.root,'diana55-camera','Camera system',[-.15,0,0],[0,.45,.45]);const top=this.group(g,'diana55-camera-top','Upper camera mounting bays · capacity reference');top.userData.capacity=4;top.userData.installedCountVerified=false;for(const [i,x] of [-.66,-.22,.22,.66].entries()){const body=this.box(top,[.20,.28,.22],[x,2.18,0],'dark',.025);body.userData.cameraBay=i+1;this.cyl(top,.055,.10,[x,2.00,0],'black','camera-lens','z');}const low=this.group(g,'diana55-camera-low','Low-angle mirror/camera path');for(const z of [-.54,.54]){const m=this.box(low,[.44,.025,.18],[-.30,1.46,z],'silver',.006);m.rotation.z=z<0?.24:-.24;}const rear=this.group(g,'diana55-camera-rear','Rear-side camera bay · capability reference');rear.userData.capacity=1;rear.userData.installedCountVerified=false;this.box(rear,[.22,.20,.20],[.35,.52,0],'dark',.025);this.cyl(rear,.05,.09,[.35,.64,0],'black','rear-camera','z');const area=this.group(g,'diana55-camera-area','Area-camera mounting bays · capacity reference');area.userData.capacity=2;area.userData.installedCountVerified=false;for(const z of [-.62,.62]){this.box(area,[.18,.22,.18],[.60,1.72,z],'dark',.02);this.cyl(area,.045,.08,[.60,1.58,z],'black','area-camera','z');}}
 buildLights(){const g=this.group(this.root,'diana55-light','LED illumination',[-.15,0,0],[0,.45,-.42]);const dome=this.group(g,'diana55-light-dome','Light-dome architecture');for(const x of [-.62,0,.62]){const a=this.box(dome,[.42,.06,1.20],[x,1.72,0],'led',.03);a.userData.inspectionLight=true;a.material=a.material.clone();a.material.userData.baseOpacity=1;for(let z=-.46;z<=.46;z+=.115){const fin=this.box(dome,[.34,.055,.018],[x,1.79,z],'silver',.002);fin.userData.mechanismRole='light-housing-cooling-fin-reference';}}const led=this.group(g,'diana55-light-led','Adjustable LED arrays');for(const z of [-.58,-.29,0,.29,.58]){const a=this.box(led,[1.46,.035,.055],[0,1.34,z],'led',.008);a.userData.inspectionLight=true;a.material=a.material.clone();a.material.userData.baseOpacity=1;}const low=this.group(g,'diana55-light-low','Low-angle illumination');for(const z of [-.66,.66]){const a=this.box(low,[1.30,.045,.055],[.10,1.10,z],'led',.008);a.rotation.x=z<0?.20:-.20;a.userData.inspectionLight=true;a.material=a.material.clone();a.material.userData.baseOpacity=1;}}
 buildProcessing(){const g=this.group(this.root,'diana55-processing','Image processing and operator interface',[1.30,0,0],[.25,.20,.52]);const compute=this.group(g,'diana55-process-compute','GPU+CPU processing cabinet');this.box(compute,[.78,1.55,.72],[0,1.08,.96],'dark',.05);for(let y=.55;y<1.55;y+=.18)this.box(compute,[.50,.035,.025],[.40,y,1.34],'steel',0);const hmi=this.group(g,'diana55-process-hmi','Operator terminal');this.box(hmi,[.70,.92,.52],[.62,.92,-1.28],'white',.05);this.box(hmi,[.48,.32,.025],[.55,1.18,-1.56],'glass',.03);const recipe=this.group(g,'diana55-process-recipe','Master / tolerance recipe storage interface');this.box(recipe,[.52,.20,.32],[.58,.72,-1.56],'blue',.025);}
 buildReject(){const g=this.group(this.root,'diana55-reject','Blank ejection / sorting',[2.42,0,0],[.52,.16,0]);g.userData.installedRejectActuationVerified=false;const gate=this.group(g,'diana55-reject-gate','Mechanical reject reference · installed type unverified');gate.userData.rejectReference='mechanical';const blade=this.box(gate,[.12,.36,1.05],[-.12,.96,0],'red',.025);blade.userData.rejectGate=true;const cyl=this.cyl(gate,.035,.26,[-.32,.83,.48],'steel','mechanical-reject-cylinder-reference','x');cyl.userData.mechanismRole='mechanical-reject-cylinder-reference';const home=this.box(gate,[.045,.055,.040],[-.18,1.12,-.46],'green',.004);home.userData.mechanismRole='mechanical-reject-home-sensor-reference';
 const air=this.group(g,'diana55-reject-air','Air-nozzle reject reference · installed type unverified');air.userData.rejectReference='air-nozzle';for(const z of [-.36,-.12,.12,.36]){const n=this.cyl(air,.018,.08,[-.14,.91,z],'blue','reject-air-nozzle','x');n.userData.rejectAirNozzle=true;}const valve=this.box(air,[.18,.12,.16],[-.38,.62,.58],'steel',.012);valve.userData.mechanismRole='reject-air-solenoid-manifold-reference';
 const chute=this.group(g,'diana55-reject-chute','Reject collection path');this.box(chute,[1.05,.08,.66],[.35,.55,.58],'steel',.02);this.box(chute,[.72,.40,.66],[.62,.36,.58],'light',.03);const sensor=this.group(g,'diana55-reject-sensor','Reject confirmation sensing');for(const z of [-.42,.42])this.box(sensor,[.08,.16,.10],[-.55,1.08,z],'blue',.015);}
 buildDelivery(){const g=this.group(this.root,'diana55-delivery','Accepted blank delivery',[3.55,0,0],[.72,.16,0]);const belt=this.group(g,'diana55-delivery-belt','Accepted-product belt');for(const z of [-.44,-.15,.15,.44]){this.box(belt,[1.45,.025,.10],[0,.76,z],'rubber',.006);for(const x of [-.62,.62])this.cyl(belt,.055,.14,[x,.75,z],'steel','delivery-pulley','z');}const stack=this.group(g,'diana55-delivery-stack','Delivery stack / buffer interface');this.box(stack,[.72,.08,1.02],[.78,.43,0],'steel');const counter=this.group(g,'diana55-delivery-counter','Output sensing / counter');for(const z of [-.38,.38])this.box(counter,[.08,.16,.10],[.48,1.02,z],'green',.015);}
 buildExteriorIdentity(){
  const g=this.group(this.root,'diana55-exterior-v235','Diana Eye 55 official-family exterior identity polish');
  this.root.userData.visualRefinement='V235_DIANA_EYE55_WHITE_INSPECTION_CELL_WITH_HMI_PEDESTAL';
  this.root.userData.visualEvidenceBoundary='HEIDELBERG_MASTERWORK_DIANA_EYE_42_55_OFFICIAL__INSTALLED_CAMERA_REJECT_OPTIONS_BOUNDED';
  g.userData.sourceBoundary=this.root.userData.visualEvidenceBoundary;
  for(const z of [-.90,.90]){
   const base=this.cover(this.box(g,[3.55,.50,.10],[.05,.55,z],'light',.035));base.userData.silhouetteCritical=true;
   const crown=this.cover(this.box(g,[2.28,.16,.12],[-.12,2.54,z],'white',.030));crown.userData.silhouetteCritical=true;
   this.cover(this.box(g,[.14,1.76,.11],[-1.18,1.55,z],'white',.025));
   this.cover(this.box(g,[.14,1.76,.11],[.88,1.55,z],'white',.025));
   const aperture=this.box(g,[1.46,.82,.025],[-.15,1.54,z+(z<0?-.055:.055)],'glass',.035);aperture.userData.inspectionAperture=true;aperture.userData.silhouetteCritical=true;
  }
  const hood=this.cover(this.box(g,[2.18,.30,1.76],[-.15,2.43,0],'white',.055));hood.userData.cameraHood=true;hood.userData.silhouetteCritical=true;
  const feederFascia=this.cover(this.box(g,[1.22,.30,.10],[-3.36,.62,-.88],'light',.025));feederFascia.userData.feederIdentityPanel=true;
  const outputFascia=this.cover(this.box(g,[1.28,.30,.10],[3.47,.62,-.88],'light',.025));outputFascia.userData.acceptedDeliveryPanel=true;
  // Diana Eye product imagery shows a separate operator touchscreen pedestal beside the inspection cell.
  const hmi=this.group(g,'diana55-hmi-pedestal-v235','Separate touchscreen pedestal reference');
  const pedestal=this.cover(this.box(hmi,[.52,1.02,.42],[1.72,.70,-1.48],'light',.050));pedestal.userData.silhouetteCritical=true;
  const screen=this.box(hmi,[.38,.28,.025],[1.72,1.16,-1.705],'glass',.025);screen.userData.mechanismRole='diana-eye-hmi-display-reference';
  this.cyl(hmi,.038,.70,[1.72,.36,-1.48],'steel','pedestal-foot-reference','y');
 }
 enrichV141(){this.root.userData.researchVersion='V141';this.root.userData.researchSourceCount=V141_SOURCE_STATS.total;this.root.userData.uniqueResearchUrls=V141_SOURCE_STATS.uniqueUrls;this.root.userData.detailPass='V141_DIANA55_TRIGGER_CAPTURE_DECISION_EJECTION';
  const tag=(m,role,evidence='MASTERWORK_DIANA_EYE_55_OEM')=>{if(m){m.userData.mechanismRole=role;m.userData.evidence=evidence;m.userData.detail=true;}return m;};
  const feeder=this.findNode('diana55-feed-friction');if(feeder){
    const knife=tag(this.box(feeder,[.08,.22,1.02],[.62,.91,0],'steel',.008),'patented-feeding-knife-reference','MASTERWORK_42_55_OEM');knife.rotation.z=-.16;
    tag(this.cyl(feeder,.055,.18,[-.18,.50,.58],'dark','vibration-motor-reference','x'),'vibration-motor-reference','MASTERWORK_42_55_OEM');
    const air=this.group(feeder,'diana55-feed-air-v123','Feeder air-blowing manifold',[0,0,0],[.10,.12,.12]);
    tag(this.cyl(air,.018,1.00,[.10,.68,0],'steel','air-manifold','z'),'feeder-air-manifold','MASTERWORK_42_55_OEM');
    for(const z of [-.40,-.20,0,.20,.40])tag(this.cyl(air,.010,.08,[.28,.70,z],'blue','air-nozzle','x'),'feeder-air-blowing-nozzle','MASTERWORK_42_55_OEM');
  }
  const dbl=this.findNode('diana55-feed-double');if(dbl){
    dbl.userData.oemTechnology='ULTRASONIC_DOUBLE_SHEET_DETECTION';
    for(const z of [-.36,.36]){
      tag(this.box(dbl,[.055,.11,.055],[.58,1.05,z],'blue',.008),'ultrasonic-double-sheet-emitter','MASTERWORK_42_55_OEM');
      tag(this.box(dbl,[.055,.11,.055],[.74,1.05,z],'green',.008),'ultrasonic-double-sheet-receiver','MASTERWORK_42_55_OEM');
    }
  }
  const top=this.findNode('diana55-camera-top');if(top){top.userData.oemCameraOptions=['8K color','4K high-speed color','8K B/W'];top.userData.installedCountVerified=false;for(const m of top.children.filter(o=>o.isMesh&&o.userData.mechanismRole==='camera-lens'))tag(m,'line-scan-camera-lens','MASTERWORK_DIANA_EYE_55_OEM');}
  const area=this.findNode('diana55-camera-area');if(area){area.userData.oemCapacity=2;area.userData.installedCountVerified=false;}
  const rear=this.findNode('diana55-camera-rear');if(rear){rear.userData.oemCapacity=1;rear.userData.installedCountVerified=false;}
  const lights=this.findNode('diana55-light');if(lights){lights.userData.oemIlluminationModes=4;lights.userData.softwareAdjustableIntensity=true;lights.userData.patentedLightDome=true;}
  const transport=this.findNode('diana55-transport');if(transport){transport.userData.transportType='SUCTION_BELT_OEM';transport.userData.triggerEncoderChain='FUNCTIONAL_REFERENCE';}
  const trig=this.findNode('diana55-transport-trigger');if(trig)trig.userData.captureInterlock='BLANK_PRESENT_AND_TRANSPORT_ENCODER';
  const reject=this.findNode('diana55-reject');if(reject){reject.userData.inlineFaultBlankEjectionConfirmed=true;reject.userData.installedRejectActuationVerified=false;reject.userData.boundary='OEM confirms inline ejection, but public source does not identify installed actuator type.';}
  const sensor=this.findNode('diana55-reject-sensor');if(sensor)for(const m of sensor.children.filter(o=>o.isMesh))tag(m,'reject-confirmation-sensor','MASTERWORK_DIANA_EYE_55_OEM');
 }
 findNode(id){return id==='diana55-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;let count=0;for(const m of this.meshes)if(m.userData.exteriorCover){m.visible=!on;count++;}this.root.userData.interiorCutawayVisible=!!on;this.root.userData.exteriorHiddenCount=on?count:0;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){const open=this.exteriorOpen;this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);this.setExteriorOpen(open);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
