import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {fz1200SpecFor} from './data/dimensions-fz1200.js';import {fz1200TaxonomyFor} from './data/taxonomy-fz1200.js';import {FZ1200_ORIENTATION,FZ1200_TECHNICAL_SOURCES} from './data/sources-fz1200.js';
const V=a=>new THREE.Vector3(...a);
export class FZ1200MachineTemplate{
 constructor(assetId='BMJ-MCH-0007'){this.spec=fz1200SpecFor(assetId);this.root=new THREE.Group();this.root.name=this.spec.siteLabel+' · FZ 1200';this.root.userData={assetId:this.spec.assetId,nodeId:'fz1200-root',spec:this.spec,sources:FZ1200_TECHNICAL_SOURCES,orientation:FZ1200_ORIENTATION,taxonomyVersion:'fz1200-v2',evidenceGrade:'MODEL_FAMILY_PROCESS_GROUNDED',engineeringDimensions:false,geometryStatus:'DEDICATED_FAMILY_PROCESS_REFERENCE__INSTALLED_OPTIONS_BOUNDED'};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=fz1200TaxonomyFor(this.spec.assetId);this.taxonomyById=new Map(this.taxonomy.map(n=>[n.id,n]));for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'FAMILY_PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={white:0xe8e9e6,dark:0x293035,steel:0x89959a,silver:0xc4cbcd,blue:0x3d708a,red:0xb13d34,green:0x568372,yellow:0xd5aa47,black:0x111719,paper:0xd8c59c,pallet:0x9d7448,glass:0x6fa0ad}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.48:.08,roughness:k==='paper'?.88:.46,transparent:k==='glass',opacity:k==='glass'?.34:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,24),'c'+r+l+axis,k,p,rot);
  const rotating=/^(trunnion-shaft|rotation-gear|blower|vibration|hyd-pump)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;
  if(rotating)m.userData.spinDirection=/^(trunnion-shaft|rotation-gear)$/.test(role)?1:-1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildBase();this.buildClamp();this.buildTurn();this.buildAir();this.buildJog();this.buildHydraulic();this.buildControl();}
 buildBase(){const g=this.group(this.root,'fz1200-base','Base and lift');const frame=this.group(g,'fz1200-base-frame','Floor base frame');this.box(frame,[2.55,.22,2.02],[0,.11,0],'dark',.04);for(const z of [-.78,.78])this.box(frame,[2.25,.12,.12],[0,.30,z],'steel',.02);const lift=this.group(g,'fz1200-base-lift','Vertical lift carriage');for(const x of [-.88,.88])this.box(lift,[.16,2.05,.16],[x,1.26,0],'steel',.025);const pallet=this.group(g,'fz1200-base-pallet','Lower pallet platform');this.box(pallet,[1.42,.12,1.02],[0,.52,0],'steel',.02);for(const z of [-.38,0,.38])this.box(pallet,[1.30,.07,.16],[0,.62,z],'pallet',.01);}
 buildClamp(){const pivotY=1.36,g=this.group(this.root,'fz1200-clamp','Pile clamp assembly',[0,pivotY,0],[0,.34,.30]);g.userData.turnPivotY=pivotY;g.userData.clampStrokeReference=.47;
  const upper=this.group(g,'fz1200-clamp-upper','Upper clamp plate');this.box(upper,[1.45,.14,1.05],[0,.66,0],'steel',.025);upper.userData.clampMoving=true;
  const lower=this.group(g,'fz1200-clamp-lower','Lower clamp / pallet plate');this.box(lower,[1.45,.14,1.05],[0,-.66,0],'steel',.025);
  const column=this.group(g,'fz1200-clamp-column','Clamp guide columns');for(const x of [-.64,.64])for(const z of [-.43,.43])this.cyl(column,.045,1.28,[x,0,z],'silver','clamp-guide','y');
  const pile=this.group(g,'fz1200-pile','Reference paper pile');this.box(pile,[1.20,.72,.80],[0,-.24,0],'paper',.012);}
 buildTurn(){const pivotY=1.36,g=this.group(this.root,'fz1200-turn','Turning yoke / trunnion',[0,0,0],[.35,.20,0]);
  const yoke=this.group(g,'fz1200-turn-yoke','Rotating yoke',[0,pivotY,0]);for(const x of [-.98,.98])this.box(yoke,[.16,1.78,1.45],[x,-.01,0],'blue',.04);this.box(yoke,[2.08,.15,1.42],[0,.84,0],'blue',.03);yoke.userData.rotatingAssembly=true;yoke.userData.turnPivotY=pivotY;
  const tr=this.group(g,'fz1200-turn-trunnion','Trunnion bearings');for(const z of [-.86,.86]){this.cyl(tr,.28,.18,[0,1.37,z],'steel','trunnion','z');this.cyl(tr,.12,.24,[0,1.37,z],'dark','trunnion-shaft','z');}
  const drive=this.group(g,'fz1200-turn-drive','Rotation drive interface');this.cyl(drive,.22,.24,[.58,.48,.94],'dark','rotation-drive','z');this.cyl(drive,.10,.28,[.58,.48,.94],'steel','rotation-gear','z');}
 buildAir(){const g=this.group(this.root,'fz1200-air','Air separation / dust removal',[0,0,0],[0,.22,.45]);const blower=this.group(g,'fz1200-air-blower','High-pressure air blower reference');this.cyl(blower,.24,.48,[-.82,.48,1.12],'dark','blower','x');this.box(blower,[.48,.40,.42],[-.82,.48,1.12],'blue',.04);const nozzle=this.group(g,'fz1200-air-nozzle','Air-jet manifold · visualization reference');nozzle.userData.exactNozzleCountVerified=false;for(const z of [-.44,-.22,0,.22,.44]){const n=this.cyl(nozzle,.018,.22,[-.72,1.28,z],'silver','air-nozzle','x');n.userData.airNozzle=true;}const dust=this.group(g,'fz1200-air-dust','Dust / powder collection path');this.box(dust,[.72,.36,.56],[.82,.48,1.10],'dark',.04);this.cyl(dust,.08,.72,[.34,.62,1.10],'steel','dust-duct','x');}
 buildJog(){const g=this.group(this.root,'fz1200-jog','Jogging / alignment',[0,0,0],[0,.20,-.42]);const side=this.group(g,'fz1200-jog-side','Side jogger plates');for(const z of [-.50,.50]){const p=this.box(side,[1.16,.62,.06],[0,1.18,z],'yellow',.015);p.userData.jogger=true;p.userData.jogAxis='z';}const front=this.group(g,'fz1200-jog-front','Front/back alignment plates');for(const x of [-.64,.64]){const p=this.box(front,[.06,.62,.78],[x,1.18,0],'yellow',.015);p.userData.jogger=true;p.userData.jogAxis='x';}const vib=this.group(g,'fz1200-jog-vibration','Vibration drive reference');this.cyl(vib,.13,.22,[0,.65,-.72],'dark','vibration','z');}
 buildHydraulic(){const g=this.group(this.root,'fz1200-hydraulic','Hydraulic drive',[0,0,0],[0,.18,.55]);const cyl=this.group(g,'fz1200-hyd-cylinder','Lift / clamp hydraulic cylinders');for(const x of [-.80,.80]){const c=this.cyl(cyl,.07,.78,[x,1.04,.72],'steel','hyd-cylinder','y');c.userData.hydraulicCylinder=true;}const power=this.group(g,'fz1200-hyd-power','Hydraulic power pack');this.box(power,[.62,.52,.52],[.90,.48,-1.10],'dark',.04);this.cyl(power,.12,.38,[.75,.76,-1.10],'blue','hyd-pump','x');const hose=this.group(g,'fz1200-hyd-hose','Hydraulic routing interface');for(const z of [-.18,.18])this.cyl(hose,.015,1.25,[.72,1.10,z],'black','hose','y');}
 buildControl(){const g=this.group(this.root,'fz1200-control','Safety and control',[0,0,0],[.45,.16,-.55]);const hmi=this.group(g,'fz1200-control-hmi','Operator control panel');this.box(hmi,[.58,.82,.42],[-1.28,.74,-1.12],'dark',.05);this.box(hmi,[.36,.24,.024],[-1.34,1.02,-1.35],'glass',.02);const safe=this.group(g,'fz1200-control-safety','Interlock / E-stop architecture');for(const x of [-1.17,-1.03,-.89])this.cyl(safe,.032,.025,[x,.80,-1.35],x===-.89?'red':'green','button','z');const guard=this.group(g,'fz1200-control-guard','Perimeter guard reference');for(const x of [-1.18,1.18])for(const z of [-.98,.98])this.box(guard,[.06,1.25,.06],[x,.85,z],'steel',.01);}
 findNode(id){return id==='fz1200-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;this.root.userData.interiorCutawayVisible=!!on;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
