import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {fz1200SpecFor} from './data/dimensions-fz1200.js';import {fz1200TaxonomyFor} from './data/taxonomy-fz1200.js';import {FZ1200_ORIENTATION,FZ1200_TECHNICAL_SOURCES} from './data/sources-fz1200.js';
const V=a=>new THREE.Vector3(...a);
export class FZ1200MachineTemplate{
 constructor(assetId='BMJ-MCH-0007'){this.spec=fz1200SpecFor(assetId);this.root=new THREE.Group();this.root.name=this.spec.siteLabel+' · FZ 1200';this.root.userData={assetId:this.spec.assetId,nodeId:'fz1200-root',spec:this.spec,sources:FZ1200_TECHNICAL_SOURCES,orientation:FZ1200_ORIENTATION,taxonomyVersion:'fz1200-v4-drive-hydraulic-interlock',detailPass:'V140_FZ1200_DRIVE_HYDRAULIC_AIR_INTERLOCK',evidenceGrade:'MODEL_IDENTIFIED_EXACT_PUBLIC_REFERENCE__OEM_UNVERIFIED',engineeringDimensions:false,geometryStatus:'FZ1200_EXACT_MODEL_PROCESS_REFERENCE__BMJ_INSTALLED_OEM_AND_DIMENSIONS_BOUNDED',exactModelVerifiedFromBMJ:true,installedOemVerified:false,exactPublicReference:this.spec.exactModelPublicReference};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=fz1200TaxonomyFor(this.spec.assetId);this.taxonomyById=new Map(this.taxonomy.map(n=>[n.id,n]));for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'FAMILY_PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={white:0xe8e9e6,dark:0x293035,steel:0x89959a,silver:0xc4cbcd,blue:0x3d708a,red:0xb13d34,green:0x568372,yellow:0xd5aa47,black:0x111719,paper:0xd8c59c,pallet:0x9d7448,glass:0x6fa0ad}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.48:.08,roughness:k==='paper'?.88:.46,transparent:k==='glass',opacity:k==='glass'?.34:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,24),'c'+r+l+axis,k,p,rot);
  const rotating=/^(trunnion-shaft|rotation-gear|blower|vibration|hyd-pump)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;
  if(rotating)m.userData.spinDirection=/^(trunnion-shaft|rotation-gear)$/.test(role)?1:-1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildBase();this.buildClamp();this.buildTurn();this.buildAir();this.buildJog();this.buildHydraulic();this.buildControl();this.refineExteriorV232();}
 buildBase(){const g=this.group(this.root,'fz1200-base','Base and lift');const frame=this.group(g,'fz1200-base-frame','Floor base frame');this.box(frame,[2.55,.22,2.02],[0,.11,0],'dark',.04);for(const z of [-.78,.78])this.box(frame,[2.25,.12,.12],[0,.30,z],'steel',.02);
  for(const x of [-1.04,1.04])for(const z of [-.82,.82]){const foot=this.cyl(frame,.055,.14,[x,.07,z],'steel','levelling-foot','y');this.tag?.(foot,'fz1200-levelling-foot-reference','FZ1200_CLOSE_FAMILY_COMPONENT_REFERENCE');}
  const lift=this.group(g,'fz1200-base-lift','Vertical lift carriage');for(const x of [-.88,.88])this.box(lift,[.16,2.05,.16],[x,1.26,0],'steel',.025);
  for(const x of [-.78,.78]){for(const y of [.46,2.04]){const sprocket=this.cyl(lift,.095,.08,[x,y,.62],'dark','lift-chain-sprocket','z');sprocket.userData.mechanismRole='lift-chain-sprocket';sprocket.userData.rotor=true;sprocket.userData.rotorAxis='z';sprocket.userData.spinDirection=1;}const chain=this.box(lift,[.035,1.52,.05],[x,1.25,.62],'steel',.006);chain.userData.mechanismRole='lift-chain-reference';}
  const fork=this.group(g,'fz1200-base-fork','Fork housing / lift crosshead reference');this.box(fork,[1.86,.20,1.26],[0,.48,0],'blue',.035);fork.userData.closeFamilyReference=true;
  const pallet=this.group(g,'fz1200-base-pallet','Lower pallet platform');this.box(pallet,[1.42,.12,1.02],[0,.52,0],'steel',.02);for(const z of [-.38,0,.38])this.box(pallet,[1.30,.07,.16],[0,.62,z],'pallet',.01);}
 buildClamp(){const pivotY=1.36,g=this.group(this.root,'fz1200-clamp','Pile clamp assembly',[0,pivotY,0],[0,.34,.30]);g.userData.turnPivotY=pivotY;g.userData.clampStrokeReference=.47;
  const upper=this.group(g,'fz1200-clamp-upper','Upper clamp plate');this.box(upper,[1.45,.14,1.05],[0,.66,0],'steel',.025);upper.userData.clampMoving=true;
  const lower=this.group(g,'fz1200-clamp-lower','Lower clamp / pallet plate');this.box(lower,[1.45,.14,1.05],[0,-.66,0],'steel',.025);
  const column=this.group(g,'fz1200-clamp-column','Clamp guide columns');for(const x of [-.64,.64])for(const z of [-.43,.43])this.cyl(column,.045,1.28,[x,0,z],'silver','clamp-guide','y');
  const pile=this.group(g,'fz1200-pile','Reference paper pile');pile.userData.layeredPileReference=true;
  for(let i=0;i<16;i++){const layer=this.box(pile,[1.20,.034,.80],[0,-.57+i*.043,0],'paper',.004);layer.userData.paperLayer=true;layer.userData.layerIndex=i;}
  const clampHyd=this.group(g,'fz1200-clamp-cylinder','Clamp hydraulic actuation reference');for(const x of [-.58,.58]){const c=this.cyl(clampHyd,.045,.42,[x,.38,.46],'steel','clamp-hyd-cylinder','y');c.userData.hydraulicCylinder=true;}
  const clampSense=this.group(g,'fz1200-clamp-sensing','Clamp position / pressure confirmation reference');for(const z of [-.42,.42]){const sen=this.box(clampSense,[.045,.055,.040],[.54,.45,z],'green',.005);sen.userData.mechanismRole='clamp-confirm-sensor';}
 }
 buildTurn(){const pivotY=1.36,g=this.group(this.root,'fz1200-turn','Turning yoke / trunnion',[0,0,0],[.35,.20,0]);
  const yoke=this.group(g,'fz1200-turn-yoke','Rotating yoke',[0,pivotY,0]);for(const x of [-.98,.98])this.box(yoke,[.16,1.78,1.45],[x,-.01,0],'blue',.04);this.box(yoke,[2.08,.15,1.42],[0,.84,0],'blue',.03);yoke.userData.rotatingAssembly=true;yoke.userData.turnPivotY=pivotY;
  const tr=this.group(g,'fz1200-turn-trunnion','Trunnion bearings');for(const z of [-.86,.86]){this.cyl(tr,.28,.18,[0,1.37,z],'steel','trunnion','z');this.cyl(tr,.12,.24,[0,1.37,z],'dark','trunnion-shaft','z');const housing=this.box(tr,[.38,.38,.16],[0,1.37,z],'dark',.04);housing.userData.mechanismRole='pivot-bearing-housing-reference';}
  const drive=this.group(g,'fz1200-turn-drive','Rotation drive interface');this.cyl(drive,.22,.24,[.58,.48,.94],'dark','rotation-drive','z');this.cyl(drive,.10,.28,[.58,.48,.94],'steel','rotation-gear','z');
  const turnCyl=this.group(g,'fz1200-turn-cylinder','Tilting / turning cylinder reference');const tc=this.cyl(turnCyl,.06,.78,[.76,.92,.66],'steel','tilting-cylinder','y');tc.rotation.z=-.42;tc.userData.closeFamilyReference=true;
  const lock=this.group(g,'fz1200-turn-lock','Turning-position locking mechanism');const pin=this.cyl(lock,.045,.22,[-.72,.60,.88],'steel','turn-lock-pin','x');pin.userData.turnLockPin=true;const body=this.box(lock,[.22,.20,.20],[-.84,.60,.88],'dark',.025);body.userData.closeFamilyReference=true;const sensor=this.box(lock,[.045,.055,.040],[-.66,.72,.88],'green',.004);sensor.userData.turnLockSensor=true;}
 buildAir(){const g=this.group(this.root,'fz1200-air','Air separation / dust removal',[0,0,0],[0,.22,.45]);const blower=this.group(g,'fz1200-air-blower','High-pressure air blower reference');this.cyl(blower,.24,.48,[-.82,.48,1.12],'dark','blower','x');this.box(blower,[.48,.40,.42],[-.82,.48,1.12],'blue',.04);const bm=this.cyl(blower,.11,.26,[-1.16,.48,1.12],'dark','blower-motor','x');bm.userData.rotor=true;bm.userData.mechanismRole='blower-motor';bm.userData.rotorAxis='x';bm.userData.spinDirection=-1;const gauge=this.cyl(blower,.055,.025,[-.48,.76,1.12],'glass','air-pressure-gauge','z');gauge.userData.mechanismRole='air-pressure-gauge';
 const nozzle=this.group(g,'fz1200-air-nozzle','Air-jet manifold · visualization reference');nozzle.userData.exactNozzleCountVerified=false;const manifold=this.cyl(nozzle,.026,1.05,[-.66,1.18,0],'steel','air-manifold','z');manifold.userData.mechanismRole='air-manifold';for(const z of [-.44,-.22,0,.22,.44]){const n=this.cyl(nozzle,.018,.22,[-.72,1.28,z],'silver','air-nozzle','x');n.userData.airNozzle=true;const v=this.cyl(nozzle,.022,.045,[-.63,1.16,z],'yellow','air-branch-valve','z');v.userData.mechanismRole='air-branch-valve';}
 const vent=this.group(g,'fz1200-air-ventilation','Ventilation plate / aerating interface reference');this.box(vent,[1.18,.055,.76],[0,1.01,0],'steel',.008);for(const z of [-.30,-.10,.10,.30])for(const x of [-.42,-.14,.14,.42]){const port=this.cyl(vent,.012,.020,[x,1.045,z],'dark','ventilation-port','y');port.userData.mechanismRole='ventilation-port';}
 const dust=this.group(g,'fz1200-air-dust','Dust / powder collection path');this.box(dust,[.72,.36,.56],[.82,.48,1.10],'dark',.04);this.cyl(dust,.08,.72,[.34,.62,1.10],'steel','dust-duct','x');}
 buildJog(){const g=this.group(this.root,'fz1200-jog','Jogging / alignment',[0,0,0],[0,.20,-.42]);const side=this.group(g,'fz1200-jog-side','Side jogger plates');for(const z of [-.50,.50]){const p=this.box(side,[1.16,.62,.06],[0,1.18,z],'yellow',.015);p.userData.jogger=true;p.userData.jogAxis='z';}const front=this.group(g,'fz1200-jog-front','Front/back alignment plates');for(const x of [-.64,.64]){const p=this.box(front,[.06,.62,.78],[x,1.18,0],'yellow',.015);p.userData.jogger=true;p.userData.jogAxis='x';}const vib=this.group(g,'fz1200-jog-vibration','Vibration tray / drive reference');this.cyl(vib,.13,.22,[0,.65,-.72],'dark','vibration','z');const gauge=this.group(g,'fz1200-jog-gauge','Gauge block reference');gauge.userData.installedGeometryVerified=false;this.box(gauge,[.18,.16,.10],[.48,.72,-.58],'steel',.008);}
 buildHydraulic(){const g=this.group(this.root,'fz1200-hydraulic','Hydraulic drive',[0,0,0],[0,.18,.55]);const cyl=this.group(g,'fz1200-hyd-cylinder','Lift / clamp hydraulic cylinders');for(const x of [-.80,.80]){const c=this.cyl(cyl,.07,.78,[x,1.04,.72],'steel','hyd-cylinder','y');c.userData.hydraulicCylinder=true;}
 const power=this.group(g,'fz1200-hyd-power','Hydraulic power pack');this.box(power,[.62,.52,.52],[.90,.48,-1.10],'dark',.04);const pump=this.cyl(power,.12,.38,[.75,.76,-1.10],'blue','hyd-pump','x');pump.userData.mechanismRole='hyd-pump';const motor=this.cyl(power,.12,.28,[.48,.76,-1.10],'dark','hyd-pump-motor','x');motor.userData.rotor=true;motor.userData.mechanismRole='hyd-pump-motor';motor.userData.rotorAxis='x';motor.userData.spinDirection=1;
 const manifold=this.box(power,[.22,.18,.20],[1.14,.76,-1.10],'steel',.018);manifold.userData.mechanismRole='hydraulic-manifold';for(const z of [-1.24,-1.10,-.96]){const valve=this.box(power,[.055,.11,.055],[1.14,.94,z],'yellow',.006);valve.userData.mechanismRole='hydraulic-solenoid-valve';}
 const pg=this.cyl(power,.055,.025,[1.31,.84,-1.10],'glass','hyd-pressure-gauge','z');pg.userData.mechanismRole='hyd-pressure-gauge';const filter=this.cyl(power,.05,.18,[.96,.39,-.86],'steel','hyd-return-filter','y');filter.userData.mechanismRole='hyd-return-filter';
 const hose=this.group(g,'fz1200-hyd-hose','Hydraulic routing interface');for(const z of [-.18,.18])this.cyl(hose,.015,1.25,[.72,1.10,z],'black','hose','y');}
 buildControl(){const g=this.group(this.root,'fz1200-control','Safety and control',[0,0,0],[.45,.16,-.55]);const hmi=this.group(g,'fz1200-control-hmi','Operator control panel');this.box(hmi,[.58,.82,.42],[-1.28,.74,-1.12],'dark',.05);this.box(hmi,[.36,.24,.024],[-1.34,1.02,-1.35],'glass',.02);const main=this.box(hmi,[.10,.16,.08],[-1.08,.55,-1.36],'yellow',.012);main.userData.mechanismRole='main-switch-reference';
 const safe=this.group(g,'fz1200-control-safety','Interlock / E-stop architecture');for(const x of [-1.17,-1.03,-.89])this.cyl(safe,.032,.025,[x,.80,-1.35],x===-.89?'red':'green','button','z');const permissive=this.box(safe,[.08,.12,.06],[-.72,.74,-1.35],'green',.008);permissive.userData.mechanismRole='turn-permissive-indicator';
 const guard=this.group(g,'fz1200-control-guard','Perimeter guard reference');guard.userData.installedGuardGeometryVerified=false;for(const x of [-1.18,1.18])for(const z of [-.98,.98])this.box(guard,[.06,1.25,.06],[x,.85,z],'steel',.01);for(const z of [-.98,.98]){const sensor=this.box(guard,[.045,.065,.045],[-1.12,.58,z],'green',.004);sensor.userData.mechanismRole='guard-interlock-sensor-reference';}
 this.root.userData.installedNozzleCountVerified=false;this.root.userData.installedBlowerLayoutVerified=false;this.root.userData.installedCylinderCountVerified=false;this.root.userData.closeFamilyComponentBoundary='RYFZ unit-description components are service references only; BMJ FZ1200 serial-specific construction remains unverified.';}
 refineExteriorV232(){
  this.root.userData.visualRefinement='V232_FZ1200_OPEN_CRADLE_SERVICE_POLISH';
  this.root.userData.homeDetailGeometryPolicy='SAME_LIVE_TEMPLATE__OPEN_CRADLE_YOKE_AND_POWERPACK_RETAINED';
  this.root.userData.familyEvidenceBoundary='FZ1200_EXACT_MODEL_PUBLIC_PROCESS_REFERENCE__BMJ_SERIAL_SPECIFIC_OEM_AND_GUARD_GEOMETRY_UNVERIFIED';
  const frame=this.findNode('fz1200-base-frame');
  if(frame){
   for(const z of [-.88,.88])for(const x of [-1.08,1.08]){
    const outrigger=this.box(frame,[.52,.10,.12],[x,.16,z],'dark',.018);outrigger.userData.silhouetteCritical=true;outrigger.userData.mechanismRole='base-outrigger-reference';
    const foot=this.cyl(frame,.055,.14,[x+(x<0?-.18:.18),.07,z],'steel','levelling-foot','y');foot.userData.detail=true;foot.userData.mechanismRole='levelling-foot-reference';
   }
  }
  const yoke=this.findNode('fz1200-turn-yoke');
  if(yoke){
   for(const x of [-.98,.98])for(const z of [-.54,.54]){
    const brace=this.box(yoke,[.10,.78,.12],[x,-.25,z],'blue',.014);brace.rotation.z=x<0?-.42:.42;brace.userData.silhouetteCritical=true;brace.userData.mechanismRole='yoke-diagonal-gusset-reference';
   }
   for(const x of [-.98,.98]){const cap=this.box(yoke,[.22,.18,1.46],[x,.78,0],'blue',.025);cap.userData.silhouetteCritical=true;cap.userData.mechanismRole='yoke-upper-side-cap-reference';}
  }
  const power=this.findNode('fz1200-hyd-power');
  if(power){
   const guard=this.cover(this.box(power,[.70,.62,.06],[.90,.52,-1.38],'blue',.028));guard.userData.silhouetteCritical=true;guard.userData.mechanismRole='hydraulic-powerpack-service-cover-reference';
   for(let y=.32;y<.68;y+=.08){const slot=this.box(power,[.34,.012,.012],[.84,y,-1.415],'dark',0);slot.userData.detail=true;slot.userData.mechanismRole='powerpack-vent-slot';}
   const handle=this.box(power,[.026,.18,.020],[1.16,.57,-1.418],'steel',.004);handle.userData.detail=true;handle.userData.mechanismRole='powerpack-door-handle';
  }
  const control=this.findNode('fz1200-control-hmi');
  if(control){
   const arm=this.box(control,[.64,.07,.08],[-.92,1.30,-1.10],'steel',.010);arm.rotation.z=-.10;arm.userData.silhouetteCritical=true;arm.userData.mechanismRole='operator-console-support-arm-reference';
  }
 } 
 findNode(id){return id==='fz1200-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;this.root.userData.interiorCutawayVisible=!!on;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(on){for(const m of this.meshes)if(m.userData.detail&&!m.userData.silhouetteCritical)m.visible=!on;}reset(){this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
