import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {media100SpecFor} from './data/dimensions-media100.js';import {media100TaxonomyFor} from './data/taxonomy-media100.js';import {MEDIA100_ORIENTATION,MEDIA100_TECHNICAL_SOURCES} from './data/sources-media100.js';
const V=a=>new THREE.Vector3(...a);
export class Media100MachineTemplate{
 constructor(assetId='BMJ-MCH-0016'){this.spec=media100SpecFor(assetId);this.root=new THREE.Group();this.root.name=this.spec.sap+' · BOBST MEDIA 100 II';this.root.userData={assetId:this.spec.assetId,nodeId:'media100-root',spec:this.spec,sources:MEDIA100_TECHNICAL_SOURCES,orientation:MEDIA100_ORIENTATION,taxonomyVersion:'media100-v1',evidenceGrade:'MODEL_FAMILY_PROCESS_GROUNDED'};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=media100TaxonomyFor(this.spec.assetId);this.taxonomyById=new Map(this.taxonomy.map(n=>[n.id,n]));for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'FAMILY_PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={ivory:0xe9e9e4,white:0xf3f3ef,dark:0x252c30,black:0x111719,steel:0x8b969b,silver:0xc1c8ca,rubber:0x252a2b,red:0xb03731,blue:0x467b93,green:0x5f8a73,glue:0xd3ab46,paper:0xd8c59d,glass:0x7db0bb}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.5:.08,roughness:(k==='rubber')?.72:.44,transparent:k==='glass',opacity:k==='glass'?.30:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}cyl(g,r,l,p,k='steel',role='',axis='z'){const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,20),'c'+r+l,k,p,rot);m.userData.rotor=true;m.userData.mechanismRole=role;return m;}cover(m){m.userData.exteriorCover=true;return m;}
 railPair(g,x,w,y=.78){for(const z of [-.70,.70])this.box(g,[w,.055,.055],[x,y,z],'steel',.008);}
 beltBed(g,x,w,y=.77,count=6){for(let i=0;i<count;i++){const z=-.64+i*(1.28/Math.max(1,count-1));const b=this.box(g,[w,.025,.09],[x,y,z],'rubber',.006);b.userData.belt=true;}}
 build(){this.buildAccess();this.buildFeeder();this.buildPrefold();this.buildForming();this.buildGlue();this.buildFinal();this.buildCompression();this.buildDrive();}
 buildAccess(){const g=this.group(this.root,'media100-access','Frame, rails and guards');const frame=this.group(g,'media100-access-frame','Modular side frames');for(let x=-5.10;x<=4.80;x+=1.05)for(const z of [-.82,.82]){this.box(frame,[.09,.78,.09],[x,.53,z],'ivory',.015);this.box(frame,[.92,.10,.08],[x,.88,z],'ivory',.015);}const rail=this.group(g,'media100-access-rail','Crossbars and adjustment rails');for(let x=-4.8;x<=4.6;x+=.75)this.cyl(rail,.022,1.74,[x,1.18,0],'steel','crossbar','z');const guard=this.group(g,'media100-access-guard','Safety covers');for(const [x,w] of [[-4.75,.85],[-1.55,.90],[2.15,.95],[4.35,.80]]){this.cover(this.box(guard,[w,.48,.08],[x,.55,-.91],'white',.04));this.cover(this.box(guard,[w,.48,.08],[x,.55,.91],'white',.04));}}
 buildFeeder(){const g=this.group(this.root,'media100-feeder','Blank feeder',[-4.72,0,0],[-.75,.16,0]);const stack=this.group(g,'media100-feed-stack','Blank stack support');this.box(stack,[1.10,.08,1.50],[-.18,.40,0],'steel');for(let i=0;i<12;i++)this.box(stack,[.66,.012,1.00],[-.28,.48+i*.013,0],'paper',.002);const belts=this.group(g,'media100-feed-belts','Friction feeder belts');this.beltBed(belts,.35,.95,.76,7);for(const z of [-.60,-.30,0,.30,.60])this.cyl(belts,.055,.18,[.72,.74,z],'rubber','feeder-pulley','z');const vib=this.group(g,'media100-feed-vibrator','Vibrator / separation');this.box(vib,[.42,.22,1.35],[-.60,.94,0],'dark',.03);for(const z of [-.48,-.16,.16,.48])this.box(vib,[.08,.28,.05],[-.36,1.04,z],'steel',.01);}
 buildPrefold(){const g=this.group(this.root,'media100-prefold','Alignment and pre-fold',[-3.20,0,0],[-.42,.18,0]);const guides=this.group(g,'media100-prefold-guides','Adjustable carton guides');this.railPair(guides,0,2.25,1.04);for(const z of [-.58,.58])this.box(guides,[2.20,.07,.04],[0,1.01,z],'blue',.008);const br=this.group(g,'media100-prefold-break','Left/right pre-break architecture');for(const z of [-.56,.56]){const r=this.box(br,[1.55,.06,.07],[.15,1.02,z],'steel',.008);r.rotation.z=z<0?.11:-.11;}const belts=this.group(g,'media100-prefold-belts','Transport belts');this.beltBed(belts,0,2.35,.77,7);}
 buildForming(){const g=this.group(this.root,'media100-forming','Folding / lock-bottom conversion',[-1.25,0,0],[0,.24,.35]);const bottom=this.group(g,'media100-form-bottom','Crash-lock folding architecture');for(const z of [-.56,-.28,.28,.56]){const hook=this.box(bottom,[.46,.055,.065],[-.05,1.00,z],'steel',.008);hook.rotation.z=z<0?.35:-.35;hook.userData.folderHook=true;}const servo=this.group(g,'media100-form-servo','Back-fold / corner-conversion mounting zone');for(const z of [-.72,.72]){this.cyl(servo,.13,.18,[.62,.68,z],'dark','forming-servo','z');this.box(servo,[.48,.06,.06],[.38,.92,z],'steel');}const belts=this.group(g,'media100-form-belts','Forming belts');this.beltBed(belts,0,2.15,.77,6);}
 buildGlue(){const g=this.group(this.root,'media100-glue','Glue application',[.48,0,0],[0,.24,.40]);const lower=this.group(g,'media100-glue-lower','Lower disc-glue architecture');for(const z of [-.52,.52])this.cyl(lower,.13,.055,[-.35,.87,z],'glue','glue-disc','z');const upper=this.group(g,'media100-glue-upper','Upper glue-head mounting rail');this.box(upper,[1.55,.06,.06],[.10,1.38,0],'steel');for(const z of [-.42,0,.42]){const h=this.box(upper,[.12,.22,.10],[.18,1.23,z],'dark',.02);h.userData.glueHeadPosition=true;}const pump=this.group(g,'media100-glue-pump','Glue supply / pump interface');this.box(pump,[.46,.58,.42],[.56,.52,.98],'blue',.04);this.cyl(pump,.07,.30,[.56,.83,.98],'steel','glue-pump','x');this.beltBed(g,0,1.80,.77,6);}
 buildFinal(){const g=this.group(this.root,'media100-final','Final fold / trombone',[2.35,0,0],[.28,.22,.40]);const trom=this.group(g,'media100-final-trombone','Trombone belts');for(const z of [-.55,-.28,.28,.55]){const b=this.box(trom,[2.35,.04,.10],[0,.88,z],'rubber',.008);b.userData.tromboneBelt=true;for(const x of [-1.0,1.0])this.cyl(trom,.07,.14,[x,.87,z],'steel','trombone-pulley','z');}const fold=this.group(g,'media100-final-fold','Final folding rails');for(const z of [-.62,.62]){const r=this.box(fold,[1.95,.055,.055],[-.10,1.17,z],'steel',.008);r.rotation.z=z<0?.16:-.16;}const kick=this.group(g,'media100-final-kicker','Kicker / spacing interface');const k=this.box(kick,[.08,.35,1.12],[.94,1.02,0],'green',.02);k.userData.kicker=true;}
 buildCompression(){const g=this.group(this.root,'media100-compression','Compression delivery',[4.45,0,0],[.72,.16,0]);const belts=this.group(g,'media100-press-belts','Compression belts');for(const y of [.73,1.02])for(const z of [-.52,-.17,.17,.52]){const b=this.box(belts,[1.70,.04,.10],[0,y,z],'rubber',.008);b.userData.compressionBelt=true;}const press=this.group(g,'media100-press-pressure','Pneumatic pressure setting');for(const z of [-.68,.68]){this.cyl(press,.05,.42,[-.48,1.28,z],'steel','pressure-cylinder','x');this.box(press,[1.35,.055,.06],[.12,1.19,z],'steel');}const exit=this.group(g,'media100-press-exit','Delivery / counter interface');this.box(exit,[.82,.10,1.45],[1.08,.73,0],'steel');for(const z of [-.52,-.17,.17,.52])this.cyl(exit,.06,.14,[1.13,.80,z],'rubber','exit-roller','z');}
 buildDrive(){const g=this.group(this.root,'media100-drive','Main drive and controls',[0,0,0],[0,.18,.60]);const motor=this.group(g,'media100-drive-motor','Main drive motor');this.cyl(motor,.22,.62,[-.45,.40,1.12],'dark','main-motor','x');for(let x=-.24;x<=.24;x+=.08)this.box(motor,[.025,.34,.64],[x-.45,.40,1.12],'steel');const trans=this.group(g,'media100-drive-transmission','Line-shaft / transmission reference');for(const x of [-3.3,-1.2,.8,2.8])this.cyl(trans,.11,.16,[x,.36,1.02],'steel','line-drive','z');this.cyl(trans,.035,7.0,[-.25,.36,1.02],'dark','line-shaft','x');const control=this.group(g,'media100-drive-control','CUBE-era control architecture');this.box(control,[.66,.74,.42],[-2.75,.78,-1.05],'dark',.05);this.box(control,[.40,.26,.024],[-2.80,1.06,-1.28],'glass',.02);for(const x of [-2.55,-2.42,-2.29])this.cyl(control,.032,.025,[x,.84,-1.28],x===-2.29?'red':'green','button','z');}
 findNode(id){return id==='media100-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;let count=0;for(const m of this.meshes)if(m.userData.exteriorCover){m.visible=!on;count++;}this.root.userData.interiorCutawayVisible=!!on;this.root.userData.exteriorHiddenCount=on?count:0;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){const open=this.exteriorOpen;this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);this.setExteriorOpen(open);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
