import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mk920SpecFor} from './data/dimensions-mk920.js';import {mk920TaxonomyFor} from './data/taxonomy-mk920.js';import {MK920_ORIENTATION,MK920_TECHNICAL_SOURCES} from './data/sources-mk920.js';
const V=a=>new THREE.Vector3(...a);
export class MK920MachineTemplate{
 constructor(assetId='BMJ-MCH-0011'){this.spec=mk920SpecFor(assetId);this.root=new THREE.Group();this.root.name=this.spec.sap+' · '+this.spec.model;this.root.userData={assetId:this.spec.assetId,nodeId:'mk920-root',spec:this.spec,sources:MK920_TECHNICAL_SOURCES,orientation:MK920_ORIENTATION,taxonomyVersion:'mk920-v3',evidenceGrade:'MODEL_IDENTIFIED_PROCESS_GROUNDED',geometryStatus:'DEDICATED_MODEL_PROCESS_REFERENCE__INSTALLED_OPTIONS_BOUNDED',engineeringDimensions:false};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=mk920TaxonomyFor(this.spec.assetId);this.taxonomyById=new Map(this.taxonomy.map(n=>[n.id,n]));for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={ivory:0xe5e6df,green:0x467362,dark:0x20292b,black:0x101517,steel:0x879399,silver:0xc2cbce,rubber:0x23282a,paper:0xf0ead7,gold:0xc9a13b,copper:0xae633f,red:0xa84338,glass:0x75b7c7}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver','gold','copper'].includes(k)?.58:.12,roughness:k==='paper'?.9:.46,transparent:k==='glass',opacity:k==='glass'?.32:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,24),'c'+r+l+axis,k,p,rot);
  const rotating=/^(lift-chain|blower|feed-wheel|eccentric|foil-reel|reel-shaft|foil-pull-\d+|foil-idler|foil-guide|waste-rewind|chain-sprocket|index-cam|release-cam|main-motor|flywheel|clutch)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;m.userData.reciprocator=role==='sucker';
  if(rotating)m.userData.spinDirection=/^(foil-idler|foil-guide|chain-sprocket|flywheel|clutch)$/.test(role)?-1:1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildAccess();this.buildFeeder();this.buildRegister();this.buildPlaten();this.buildFoil();this.buildTransport();this.buildDelivery();this.buildDrive();}
 buildAccess(){const g=this.group(this.root,'mk920-access','Frame, guarding and access');const frame=this.group(g,'mk920-access-frame','Monobloc side frames');for(const z of [-1.34,1.34]){this.box(frame,[3.25,2.35,.16],[.25,1.47,z],'green',.06);this.box(frame,[1.10,.55,.20],[-2.14,.55,z],'green',.04);this.box(frame,[1.55,.55,.20],[2.58,.55,z],'green',.04);}const guard=this.group(g,'mk920-access-guard','Interlocked guarding');for(const z of [-1.48,1.48]){this.cover(this.box(guard,[3.02,1.78,.09],[.22,1.64,z],'ivory',.06));this.cover(this.box(guard,[.92,1.14,.09],[-2.04,1.18,z],'ivory',.06));}const platform=this.group(g,'mk920-access-platform','Operator platform');this.box(platform,[5.45,.12,.48],[.15,.28,-1.72],'black');for(let x=-2.3;x<2.8;x+=.65)this.box(platform,[.42,.025,.50],[x,.36,-1.72],'steel',0);}
 buildFeeder(){const g=this.group(this.root,'mk920-feeder','Pile feeder',[-3.05,0,0],[-.8,.18,0]);this.cover(this.box(g,[1.62,1.55,2.26],[0,1.18,0],'ivory',.08));const pile=this.group(g,'mk920-feeder-pile','Pile lift');this.box(pile,[1.05,.08,1.34],[-.26,.42,0],'steel');this.box(pile,[1.01,.88,1.29],[-.26,.90,0],'paper');for(const z of [-.55,.55]){this.cyl(pile,.05,.10,[-.65,.42,z],'black','lift-chain');this.cyl(pile,.05,.10,[.23,.42,z],'black','lift-chain');}const head=this.group(g,'mk920-feeder-head','Suction feeding head');this.box(head,[.68,.28,1.26],[.35,1.96,0],'dark');for(const z of [-.45,-.15,.15,.45]){this.cyl(head,.03,.15,[.52,1.75,z],'rubber','sucker');this.box(head,[.04,.24,.04],[.52,1.86,z],'steel');}const air=this.group(g,'mk920-feeder-air','Blower and air manifold');this.cyl(air,.18,.48,[-.55,2.05,.78],'dark','blower','x');this.box(air,[.70,.10,.10],[-.12,2.02,.78],'steel');}
 buildRegister(){const g=this.group(this.root,'mk920-register','Registration table',[-1.86,0,0],[-.35,.18,0]);const table=this.group(g,'mk920-register-table','Feed table');this.box(table,[1.46,.12,1.52],[0,1.02,0],'steel');for(const z of [-.54,-.18,.18,.54])this.cyl(table,.032,1.10,[0,1.11,z],'rubber','feed-wheel');const front=this.group(g,'mk920-register-front','Front lays');for(const z of [-.42,.42])this.box(front,[.07,.14,.12],[.58,1.15,z],'gold');const side=this.group(g,'mk920-register-side','Side lay');this.box(side,[.18,.11,.14],[.28,1.15,-.67],'gold');this.box(g,[1.50,.58,1.72],[0,.68,0],'dark',.04);}
 buildPlaten(){const g=this.group(this.root,'mk920-platen','Hot-foil and die-cutting platen',[.05,0,0],[0,.28,.42]);const upper=this.group(g,'mk920-platen-upper','Heated upper chase');const up=this.box(upper,[1.26,.20,1.72],[0,1.76,0],'copper');up.userData.heater=true;up.material=up.material.clone();up.material.userData.baseOpacity=1;for(let x=-.48;x<=.48;x+=.24)for(const z of [-.62,-.31,0,.31,.62]){const h=this.box(upper,[.13,.025,.17],[x,1.64,z],'gold',.01);h.userData.heater=true;h.material=h.material.clone();}const lower=this.group(g,'mk920-platen-lower','Moving lower platen');this.box(lower,[1.30,.20,1.76],[0,1.30,0],'steel');lower.userData.platenMoving=true;const chase=this.group(g,'mk920-platen-chase','Die and foil chase interface');this.box(chase,[1.12,.06,1.58],[0,1.61,0],'black');const toggle=this.group(g,'mk920-platen-toggle','Toggle and pressure drive');for(const z of [-.57,.57]){const a=this.box(toggle,[.10,.76,.12],[-.30,.84,z],'steel');a.rotation.z=.42;const b=this.box(toggle,[.10,.76,.12],[.30,.84,z],'steel');b.rotation.z=-.42;}this.cyl(toggle,.19,1.42,[0,.54,0],'dark','eccentric');}
 buildFoil(){const g=this.group(this.root,'mk920-foil','Foil unwind and advance',[-.18,0,0],[0,.55,-.5]);const unwind=this.group(g,'mk920-foil-unwind','Foil reel supports · represented count unverified');unwind.userData.installedReelCountVerified=false;for(const [i,z] of [-.78,0,.78].entries()){this.cyl(unwind,.25,.22,[-.52,2.78,z],'gold','foil-reel');this.cyl(unwind,.055,.34,[-.52,2.78,z],'steel','reel-shaft');}const pull=this.group(g,'mk920-foil-pull','Three precision foil-pull axes');for(const [i,z] of [-.78,0,.78].entries()){const r=this.cyl(pull,.075,.20,[.38,2.42,z],'rubber','foil-pull-'+(i+1));r.userData.foilPullAxis=i+1;this.cyl(pull,.045,.20,[.58,2.42,z],'steel','foil-idler');}const guide=this.group(g,'mk920-foil-guide','Foil guides and tension');for(const x of [-.42,.02,.46])this.cyl(guide,.035,1.92,[x,2.20,0],'silver','foil-guide');
 const web=this.group(g,'mk920-foil-web','Three longitudinal foil-web references');for(const z of [-.78,0,.78]){const strip=this.box(web,[1.20,.012,.12],[.02,2.03,z],'gold',.002);strip.userData.foilWeb=true;strip.userData.functionalReference=true;}const waste=this.group(g,'mk920-foil-waste','Spent foil rewind');for(const z of [-.78,0,.78])this.cyl(waste,.12,.20,[.68,2.75,z],'dark','waste-rewind');}
 buildTransport(){const g=this.group(this.root,'mk920-transport','Intermittent gripper transport',[.55,0,0],[.25,.18,0]);const chain=this.group(g,'mk920-transport-chain','Gripper chain');for(const z of [-.92,.92]){this.cyl(chain,.18,.10,[-1.60,1.14,z],'steel','chain-sprocket');this.cyl(chain,.18,.10,[1.72,1.14,z],'steel','chain-sprocket');this.box(chain,[3.32,.035,.035],[.06,1.32,z],'black');}const bars=this.group(g,'mk920-transport-bar','Intermittent gripper bars · represented count unverified');bars.userData.installedBarCountVerified=false;for(let i=0;i<6;i++){const x=-1.30+i*(2.75/5),bar=this.group(bars,'mk920-transport-gripper-'+(i+1),'Gripper bar reference '+(i+1),[x,1.30,0]);bar.userData.gripperBar=true;bar.userData.barPhase=i/6;this.box(bar,[.06,.045,1.78],[0,0,0],'steel');for(const z of [-.66,-.33,0,.33,.66])this.box(bar,[.10,.035,.05],[0,-.05,z],'gold');}const cam=this.group(g,'mk920-transport-cam','Indexing cam and rails');this.cyl(cam,.28,.16,[.02,.54,1.05],'dark','index-cam');this.box(cam,[3.15,.08,.10],[.10,.72,1.04],'steel');}
 buildDelivery(){const g=this.group(this.root,'mk920-delivery','Delivery section',[2.75,0,0],[.75,.18,0]);this.cover(this.box(g,[1.64,1.62,2.30],[0,1.20,0],'ivory',.08));const release=this.group(g,'mk920-delivery-release','Gripper release');this.cyl(release,.12,1.44,[-.48,1.56,0],'steel','release-cam');const pile=this.group(g,'mk920-delivery-pile','Delivery pile lift');this.box(pile,[1.06,.08,1.35],[.24,.42,0],'steel');this.box(pile,[1.02,.66,1.30],[.24,.79,0],'paper');const jog=this.group(g,'mk920-delivery-jog','Sheet joggers');for(const z of [-.68,.68]){const j=this.box(jog,[.12,.58,.09],[.40,1.14,z],'gold');j.userData.jogger=true;}const back=this.box(jog,[.09,.58,1.18],[.79,1.14,0],'gold');back.userData.jogger=true;}
 buildDrive(){const g=this.group(this.root,'mk920-drive','Main drive and control',[.45,0,0],[0,.2,.55]);const motor=this.group(g,'mk920-drive-motor','Main motor');this.cyl(motor,.23,.58,[.02,.42,1.50],'dark','main-motor','x');for(let x=-.20;x<=.20;x+=.08)this.box(motor,[.025,.36,.62],[x,.42,1.50],'steel');const fly=this.group(g,'mk920-drive-flywheel','Flywheel and clutch');this.cyl(fly,.42,.16,[.72,.62,1.50],'steel','flywheel');this.cyl(fly,.16,.21,[.72,.62,1.50],'dark','clutch');const control=this.group(g,'mk920-drive-control','Operator console and safety circuit');this.box(control,[.90,.64,.52],[-.98,.72,-1.68],'dark',.06);this.box(control,[.52,.34,.025],[-1.07,1.12,-1.83],'glass',.03);this.box(control,[.45,.05,.31],[-.78,.98,-1.50],'silver');}
 findNode(id){return id==='mk920-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;let count=0;for(const m of this.meshes)if(m.userData.exteriorCover){m.visible=!on;count++;}this.root.userData.interiorCutawayVisible=!!on;this.root.userData.exteriorHiddenCount=on?count:0;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){const open=this.exteriorOpen;this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);this.setExteriorOpen(open);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
