import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {POLAR115_TAXONOMY} from './data/taxonomy-polar115.js';

export class Polar115MachineTemplate{
 constructor(){
  this.root=new THREE.Group();this.root.name='POLAR-115-EM';this.parts=[];this.nodes=[];this.meshes=[];this.materials=[];this.geometries=[];this.activeMeshes=[];this.exteriorOpen=false;
  this.palette={body:0xd9ddd9,dark:0x263238,table:0x6b777c,steel:0x9ca7aa,accent:0x315e73,warning:0xd8a228,screen:0x163c35,light:0xc93636,paper:0xeee8d7};
  this.build();this.taxonomy=POLAR115_TAXONOMY;this.taxonomyById=new Map(this.taxonomy.map(n=>[n.id,n]));
  for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);
  this.root.userData={assetId:'BMJ-MCH-0001',model:'115 EM MON',serial:'5831536',geometryStatus:'DEDICATED_MODEL_REFERENCE',engineeringDimensions:false};
 }
 mat(kind,transparent=false){const m=new THREE.MeshStandardMaterial({color:this.palette[kind]??this.palette.body,metalness:['steel','table'].includes(kind)?.45:.08,roughness:kind==='screen'?.2:.55,transparent,opacity:transparent?.38:1});this.materials.push(m);return m;}
 group(parent,id,name,pos=[0,0,0],explode=[0,.18,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={nodeId:id,selectable:true,explode:new THREE.Vector3(...explode)};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mesh(g,geo,kind,pos=[0,0,0],rot=null,id=null){const x=new THREE.Mesh(geo,this.mat(kind));x.position.set(...pos);if(rot)x.rotation.set(...rot);x.castShadow=kind!=='screen';x.receiveShadow=true;x.userData={ownerId:g.userData.nodeId};if(id)x.name=id;g.add(x);this.meshes.push(x);this.geometries.push(geo);return x;}
 box(g,s,p,k='body',r=.025,id=null){return this.mesh(g,r?new RoundedBoxGeometry(...s,2,r):new THREE.BoxGeometry(...s),k,p,null,id);}
 cyl(g,r,l,p,k='steel',axis='z',id=null){return this.mesh(g,new THREE.CylinderGeometry(r,r,l,24),k,p,axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,id);}
 cover(m){m.userData.exteriorCover=true;return m;} active(m){m.userData.activeElement=true;this.activeMeshes.push(m);return m;}
 build(){
  const frame=this.group(this.root,'polar-frame','Machine Frame');this.box(frame,[2.15,.25,1.7],[0,.125,.25],'dark',.04);
  const feed=this.group(this.root,'polar-feed','Air Tables',[0,0,-.55],[0,.18,-.45]);
  for(const [id,x,w] of [['polar-feed-1',-1.72,1.22],['polar-feed-2',0,2.12],['polar-feed-3',1.72,1.22]]){const t=this.group(feed,id,'Air Table',[x,0,0]);this.box(t,[w,.12,1.15],[0,.86,0],'table',.02);for(let ix=-2;ix<=2;ix++)for(let iz=-2;iz<=2;iz++){const hole=this.cyl(t,.012,.008,[ix*w/6,.925,iz*.18],'dark','y');hole.userData.detail=true;}this.box(t,[.08,.75,.08],[-w*.38,.43,.35],'dark',.01);this.box(t,[.08,.75,.08],[w*.38,.43,.35],'dark',.01);}
  const gauge=this.group(this.root,'polar-gauge','Backgauge',[0,0,.2],[0,.25,.45]);this.box(gauge,[1.72,.18,.16],[0,1.03,.46],'accent',.02);for(const x of [-.62,0,.62])this.active(this.box(gauge,[.10,.34,.08],[x,.87,.38],'steel',.01));for(const x of [-.78,.78])this.cyl(gauge,.035,1.0,[x,.82,.02],'steel','z');this.active(this.cyl(gauge,.045,1.25,[0,.70,.02],'steel','x'));
  const clamp=this.group(this.root,'polar-clamp','Hydraulic Clamp',[0,0,-.02],[0,.35,0]);this.active(this.box(clamp,[1.78,.22,.18],[0,1.28,-.08],'warning',.02,'Clamp Beam'));for(const x of [-.68,.68])this.cyl(clamp,.07,.42,[x,1.53,-.02],'steel','y');
  const knife=this.group(this.root,'polar-knife','Knife Cutting System',[0,0,-.04],[0,.5,0]);const carrier=this.active(this.box(knife,[1.86,.22,.15],[0,1.62,-.01],'dark',.015,'Knife Carrier'));const blade=this.active(this.box(knife,[1.78,.035,.16],[0,1.49,-.045],'steel',.004,'1150 mm Knife'));blade.rotation.z=-.018;this.box(knife,[1.82,.035,.06],[0,.955,-.03],'warning',.004,'Cutting Stick');for(const x of [-.72,.72]){this.active(this.cyl(knife,.11,.16,[x,1.82,.02],'accent','z'));this.box(knife,[.10,.46,.08],[x,1.59,.02],'steel',.01);}
  const safety=this.group(this.root,'polar-safety','Safety System',[0,0,-.48],[0,.3,-.5]);for(const [id,x] of [['polar-safety-1',-.98],['polar-safety-2',.98]]){const s=this.group(safety,id,'Light Barrier Column',[x,0,0]);this.box(s,[.07,.78,.07],[0,1.18,0],'dark',.01);for(let y=.86;y<1.55;y+=.09){const led=this.cyl(s,.012,.025,[0,y,-.045],'light','z');led.userData.detail=true;}}this.box(safety,[2.02,.035,.035],[0,1.57,0],'light',.005);
  const control=this.group(this.root,'polar-control','EM Monitor Control',[1.34,0,-.14],[.45,.25,-.2]);this.cover(this.box(control,[.48,.82,.45],[0,1.26,0],'body',.045));this.box(control,[.33,.28,.025],[-.01,1.43,-.235],'screen',.015,'CRT Monitor');for(let i=0;i<12;i++)this.box(control,[.045,.025,.012],[-.13+(i%4)*.085,1.17-Math.floor(i/4)*.055,-.238],i===11?'warning':'dark',.004);
  const hyd=this.group(this.root,'polar-hyd','Hydraulic and Air Supply',[-.75,0,.48],[-.4,.2,.35]);this.active(this.box(hyd,[.62,.55,.48],[0,.55,0],'accent',.04));this.cyl(hyd,.16,.42,[-.12,.91,0],'dark','x');this.cyl(hyd,.13,.5,[.22,.48,0],'steel','y');for(let i=0;i<4;i++)this.cyl(hyd,.018,.55,[-.22+i*.14,.82,.18],'warning','y');
  const housing=this.group(this.root,'polar-housing','Main Housing');this.cover(this.box(housing,[2.12,1.58,.18],[0,1.18,.62],'body',.05));this.cover(this.box(housing,[.18,1.62,1.12],[-1.02,1.18,.18],'body',.04));this.cover(this.box(housing,[.18,1.62,1.12],[1.02,1.18,.18],'body',.04));this.cover(this.box(housing,[2.12,.18,1.12],[0,1.94,.18],'body',.04));
 }
 findNode(id){return id==='POLAR-115-EM'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData.selectable)return p;return null;}resolveTaxonomyNode(id){let m=this.taxonomyById.get(id);while(m){for(const r of m.meshRefs||[]){const n=this.findNode(r);if(n)return n;}m=m.parentId?this.taxonomyById.get(m.parentId):null;}return this.root;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?[s]:this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m));m.material.transparent=fade||m.material.transparent;m.material.opacity=fade?.14:1;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;for(const m of this.meshes)if(m.userData.exteriorCover)m.visible=!on;}setLow(on){for(const m of this.meshes)if(m.userData.detail)m.visible=!on;}reset(){this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);if(this.exteriorOpen)this.setExteriorOpen(true);}dispose(){this.geometries.forEach(g=>g.dispose());this.materials.forEach(m=>m.dispose());}
}
