import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {SHARK_N650_SPEC} from './data/dimensions-shark-n650.js';import {SHARK_N650_TAXONOMY,SHARK_N650_TAXONOMY_BY_ID} from './data/taxonomy-shark-n650.js';import {SHARK_N650_ORIENTATION,SHARK_N650_TECHNICAL_SOURCES} from './data/sources-shark-n650.js';import {V141_SOURCE_STATS} from './data/research-v141.js';
const V=a=>new THREE.Vector3(...a);
export class SharkN650MachineTemplate{
 constructor(){this.spec=SHARK_N650_SPEC;this.root=new THREE.Group();this.root.name='IPM 4 · FS-SHARK-N650-P3N1';this.root.userData={assetId:this.spec.assetId,nodeId:'shark650-root',spec:this.spec,sources:SHARK_N650_TECHNICAL_SOURCES,orientation:SHARK_N650_ORIENTATION,taxonomyVersion:'shark650-v3-trigger-return-interlock',detailPass:'V141_SHARK_N650_TRANSFER_TRIGGER_DECISION_RETURN',researchVersion:'V141',researchSourceCount:V141_SOURCE_STATS.total,uniqueResearchUrls:V141_SOURCE_STATS.uniqueUrls,evidenceGrade:'MODEL_FAMILY_PROCESS_GROUNDED',geometryStatus:'CURRENT_N650_PROCESS_REFERENCE__P3N1_OPTIONS_UNDECODED',engineeringDimensions:false};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=SHARK_N650_TAXONOMY;this.taxonomyById=SHARK_N650_TAXONOMY_BY_ID;for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'FAMILY_PROCESS_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={white:0xeaeeee,light:0xc9d0d2,dark:0x283138,black:0x111619,steel:0x879499,silver:0xc3cbcd,rubber:0x23282a,blue:0x3074a1,cyan:0x4d9bb5,red:0xb13a33,green:0x548b70,amber:0xd4a04c,paper:0xdec89f,glass:0x315663,led:0xece8d1}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.5:.08,roughness:k==='glass'?.16:.44,transparent:k==='glass',opacity:k==='glass'?.38:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='dark',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='dark',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,22),'c'+r+l+axis,k,p,rot);
  const rotating=/^(transport-pulley|vacuum-blower|good-return|bad-return)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;m.userData.reciprocator=role==='suction-cup';
  if(rotating)m.userData.spinDirection=/^(transport-pulley|bad-return)$/.test(role)?-1:1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildAccess();this.buildFeeder();this.buildTransfer();this.buildInspection();this.buildVision();this.buildProcessing();this.buildReject();this.buildReturn();this.buildExteriorIdentity();}
 buildAccess(){const g=this.group(this.root,'shark650-access','Frame, platform and guarding');const frame=this.group(g,'shark650-access-frame','Machine base frame');this.box(frame,[6.70,.28,1.86],[0,.19,0],'dark',.04);for(let x=-3.1;x<=3.1;x+=.78)for(const z of [-.78,.78])this.box(frame,[.08,.62,.08],[x,.55,z],'steel',.012);const platform=this.group(g,'shark650-access-platform','Operator platform');this.box(platform,[5.10,.13,.52],[.15,.28,-1.12],'dark');for(let x=-2.2;x<=2.45;x+=.48)this.box(platform,[.32,.022,.48],[x,.36,-1.12],'steel',0);const guard=this.group(g,'shark650-access-guard','Interlocked covers / guarding');for(const z of [-.90,.90]){this.cover(this.box(guard,[1.62,1.98,.08],[-.15,1.46,z],'white',.07));this.cover(this.box(guard,[1.20,.88,.08],[1.55,.94,z],'white',.05));}}
 buildExteriorIdentity(){
  const g=this.group(this.root,'shark650-exterior-v235','FS-SHARK N650 exterior identity polish');
  this.root.userData.visualRefinement='V235_SHARK_N650_WHITE_TOWER_DARK_BASE_BLUE_STRIPE_HMI';
  this.root.userData.visualEvidenceBoundary='FOCUSIGHT_N650_PRIMARY_PRODUCT_VISUALS__P3N1_INSTALLED_OPTION_PACKAGE_UNDECODED';
  g.userData.sourceBoundary=this.root.userData.visualEvidenceBoundary;
  for(const z of [-.91,.91]){
   const base=this.cover(this.box(g,[3.42,.56,.10],[.12,.53,z],'dark',.040));base.userData.silhouetteCritical=true;
   const crown=this.cover(this.box(g,[1.92,.16,.12],[-.12,2.58,z],'white',.030));crown.userData.silhouetteCritical=true;
   this.cover(this.box(g,[.13,1.82,.11],[-1.02,1.56,z],'white',.025));
   this.cover(this.box(g,[.13,1.82,.11],[.74,1.56,z],'white',.025));
   const window=this.box(g,[1.20,.86,.025],[-.14,1.58,z+(z<0?-.055:.055)],'glass',.035);window.userData.inspectionAperture=true;window.userData.silhouetteCritical=true;
  }
  const hood=this.cover(this.box(g,[1.86,.30,1.80],[-.14,2.46,0],'white',.050));hood.userData.visionHood=true;hood.userData.silhouetteCritical=true;
  // Focusight product imagery uses a blue horizontal accent through the white/dark chassis.
  for(const z of [-.965,.965]){const stripe=this.cover(this.box(g,[5.65,.055,.025],[-.05,.86,z],'blue',.006));stripe.userData.familyAccent=true;stripe.userData.silhouetteCritical=true;}
  this.cover(this.box(g,[1.05,.28,.10],[-2.88,.62,-.90],'light',.025));
  this.cover(this.box(g,[1.28,.28,.10],[2.50,.62,-.90],'light',.025));
  // Operator monitor on support arm is prominent in published N650 installations.
  const hmi=this.group(g,'shark650-hmi-v235','Operator monitor and support arm reference');
  this.cyl(hmi,.035,.92,[.82,1.22,-1.32],'steel','hmi-mast-reference','y');
  const arm=this.box(hmi,[.62,.06,.06],[.52,1.62,-1.32],'steel',.010);arm.rotation.z=-.16;
  const monitor=this.cover(this.box(hmi,[.48,.34,.08],[.22,1.72,-1.32],'dark',.035));monitor.userData.silhouetteCritical=true;
  this.box(hmi,[.39,.26,.025],[.22,1.72,-1.375],'glass',.020).userData.mechanismRole='shark-hmi-display-reference';
 }
 buildFeeder(){const g=this.group(this.root,'shark650-feeder','Automatic feeder',[-2.92,0,0],[-.62,.16,0]);const stack=this.group(g,'shark650-feed-stack','Input blank support');this.box(stack,[.96,.08,1.24],[-.28,.40,0],'steel');for(let i=0;i<11;i++)this.box(stack,[.60,.012,.88],[-.34,.49+i*.013,0],'paper',.002);const suction=this.group(g,'shark650-feed-suction','Suction-feeder architecture reference');suction.userData.feederModeReference='suction';suction.userData.installedModeVerified=false;this.box(suction,[.68,.24,1.05],[.22,1.16,0],'dark',.035);for(const z of [-.39,-.13,.13,.39]){this.cyl(suction,.034,.15,[.42,.96,z],'rubber','suction-cup');this.box(suction,[.035,.22,.035],[.42,1.07,z],'steel');}const manifold=this.cyl(suction,.025,.96,[.18,1.18,0],'steel','feeder-vacuum-manifold','z');manifold.userData.mechanismRole='feeder-vacuum-manifold';const valve=this.box(suction,[.13,.12,.12],[-.10,.95,.54],'blue',.012);valve.userData.mechanismRole='feeder-vacuum-control-valve-reference';const gauge=this.cyl(suction,.050,.025,[.06,1.16,.54],'glass','feeder-vacuum-gauge','z');gauge.userData.mechanismRole='feeder-vacuum-gauge';const friction=this.group(g,'shark650-feed-friction','Friction-feeder option reference');friction.userData.feederModeReference='friction';friction.userData.installedModeVerified=false;for(const z of [-.44,-.15,.15,.44]){const b=this.box(friction,[.86,.025,.10],[.38,.77,z],'rubber',.006);b.userData.feederOption='friction';}const separate=this.group(g,'shark650-feed-separate','Blank separation / air assist');for(const z of [-.46,0,.46])this.box(separate,[.08,.20,.05],[-.45,.93,z],'blue',.012);}
 buildTransfer(){const g=this.group(this.root,'shark650-transfer','Full-suction transfer',[-1.58,0,0],[-.30,.16,0]);const belt=this.group(g,'shark650-transfer-belt','Full-suction transport belts');for(const z of [-.51,-.255,0,.255,.51]){const b=this.box(belt,[1.85,.025,.11],[0,.78,z],'rubber',.006);b.userData.suctionBelt=true;for(const x of [-.76,.76])this.cyl(belt,.055,.15,[x,.77,z],'steel','transport-pulley','z');}const drive=this.group(g,'shark650-transfer-drive','Transfer drive / encoder reference');const motor=this.cyl(drive,.10,.24,[-.72,.49,.68],'dark','transfer-drive-motor','x');motor.userData.rotor=true;motor.userData.rotorAxis='x';motor.userData.spinDirection=1;const coupling=this.cyl(drive,.045,.10,[-.57,.49,.68],'blue','transfer-drive-coupling','x');coupling.userData.mechanismRole='transfer-drive-coupling';const enc=this.cyl(drive,.052,.025,[.72,.77,.68],'cyan','transfer-encoder','z');enc.userData.rotor=true;enc.userData.rotorAxis='z';enc.userData.spinDirection=-1;
 const vac=this.group(g,'shark650-transfer-vacuum','Vacuum plenum / blowers');this.box(vac,[1.78,.32,1.26],[0,.55,0],'dark',.03);for(const x of [-.50,.12,.50])this.cyl(vac,.052,.50,[x,.40,.68],'blue','vacuum-blower','x');const vm=this.cyl(vac,.025,1.50,[0,.49,.55],'steel','transfer-vacuum-manifold','x');vm.userData.mechanismRole='transfer-vacuum-manifold';const vg=this.cyl(vac,.052,.025,[.64,.61,.68],'glass','transfer-vacuum-gauge','z');vg.userData.mechanismRole='transfer-vacuum-gauge';
 const guide=this.group(g,'shark650-transfer-guide','Adjustable transport guides');for(const z of [-.63,.63])this.box(guide,[1.80,.05,.04],[0,1.02,z],'steel',.008);}
 buildInspection(){const g=this.group(this.root,'shark650-inspection','Inspection tower',[-.15,0,0],[0,.32,.42]);const tower=this.group(g,'shark650-inspection-tower','Vision tower / enclosure');this.cover(this.box(tower,[1.72,2.18,1.82],[0,1.53,0],'white',.08));const window=this.group(g,'shark650-inspection-window','Dark inspection aperture');for(const z of [-.93,.93])this.box(window,[1.18,.96,.025],[0,1.57,z],'glass',.04);const bed=this.group(g,'shark650-inspection-bed','Inspection transport bed');for(const z of [-.50,-.25,0,.25,.50]){const b=this.box(bed,[1.72,.025,.105],[0,.79,z],'rubber',.005);b.userData.inspectBelt=true;}}
 buildVision(){const g=this.group(this.root,'shark650-vision','Camera and lighting system',[-.15,0,0],[0,.45,.45]);const camera=this.group(g,'shark650-vision-camera','Configurable camera mounting array · visualization bays');camera.userData.referenceBayCount=3;camera.userData.installedCameraCountVerified=false;camera.userData.p3SuffixDecoded=false;for(const [i,x] of [-.50,0,.50].entries()){const b=this.box(camera,[.22,.30,.22],[x,2.22,0],'dark',.025);b.userData.cameraMount=i+1;this.cyl(camera,.055,.10,[x,2.03,0],'black','camera-lens','z');}const light=this.group(g,'shark650-vision-light','Software-controlled lighting array');light.userData.programControlled=true;for(const z of [-.56,-.28,0,.28,.56]){const l=this.box(light,[1.30,.035,.055],[0,1.38,z],'led',.008);l.userData.inspectionLight=true;l.material=l.material.clone();l.material.userData.baseOpacity=1;}for(const z of [-.65,.65]){const l=this.box(light,[1.10,.04,.055],[.10,1.12,z],'led',.008);l.userData.inspectionLight=true;l.material=l.material.clone();l.material.userData.baseOpacity=1;}for(const z of [-.72,.72]){const shield=this.box(light,[1.42,.40,.035],[0,1.34,z],'dark',.012);shield.userData.mechanismRole='light-column-paper-shielding-reference';}
 const trigger=this.group(g,'shark650-vision-trigger','Inspection trigger / encoder sensing');for(const z of [-.42,.42]){const p=this.box(trigger,[.08,.18,.10],[-.68,1.02,z],'cyan',.015);p.userData.mechanismRole=z<0?'inspection-trigger-emitter':'inspection-trigger-receiver';}const wheel=this.cyl(trigger,.055,.08,[-.52,.82,.56],'cyan','inspection-encoder-wheel','z');wheel.userData.rotor=true;wheel.userData.rotorAxis='z';wheel.userData.spinDirection=-1;}
 buildProcessing(){const g=this.group(this.root,'shark650-processing','Vision processing and recipe control',[.95,0,0],[.25,.18,.55]);const compute=this.group(g,'shark650-process-compute','Industrial vision computer');this.box(compute,[.72,1.48,.68],[.18,1.05,.94],'dark',.05);for(let y=.56;y<1.54;y+=.16)this.box(compute,[.46,.026,.024],[.54,y,1.28],'steel',0);const hmi=this.group(g,'shark650-process-hmi','Operator HMI');this.box(hmi,[.62,.78,.42],[.58,.95,-1.16],'white',.045);this.box(hmi,[.44,.30,.022],[.52,1.18,-1.39],'glass',.025);const recipe=this.group(g,'shark650-process-recipe','Inspection template / tolerance logic');this.box(recipe,[.45,.18,.30],[.53,.72,-1.39],'blue',.022);}
 buildReject(){const g=this.group(this.root,'shark650-reject','Reject separation',[1.62,0,0],[.42,.16,0]);g.userData.installedRejectTypeVerified=false;const plate=this.group(g,'shark650-reject-plate','Plate-reject family reference');plate.userData.rejectReference='plate';const p=this.box(plate,[.11,.38,1.10],[-.05,.95,0],'red',.025);p.userData.rejectGate=true;const cyl=this.cyl(plate,.040,.30,[-.28,.80,.48],'steel','plate-reject-cylinder-reference','x');cyl.userData.mechanismRole='plate-reject-cylinder-reference';const sol=this.box(plate,[.14,.12,.12],[-.46,.60,.52],'blue',.010);sol.userData.mechanismRole='reject-solenoid-reference';const air=this.group(g,'shark650-reject-air','Air-reject family reference');air.userData.rejectReference='air';this.box(air,[.58,.08,.08],[-.35,1.20,.64],'blue',.012);for(const x of [-.22,-.07,.08])this.cyl(air,.018,.09,[x,1.13,.64],'steel','air-nozzle','x');const track=this.group(g,'shark650-reject-track','Reject tracking / confirmation');for(const z of [-.43,.43])this.box(track,[.08,.16,.10],[.40,1.02,z],'cyan',.015);}
 buildReturn(){const g=this.group(this.root,'shark650-return','Good/bad product return and collection reference',[2.72,0,0],[.68,.16,0]);g.userData.installedCollectionModeVerified=false;const good=this.group(g,'shark650-return-good','Accepted-product return belt');for(const z of [-.38,-.13,.13,.38]){this.box(good,[1.55,.025,.10],[0,.77,z-.18],'rubber',.006);for(const x of [-.65,.65])this.cyl(good,.052,.14,[x,.76,z-.18],'steel','good-return','z');}const gm=this.cyl(good,.09,.22,[-.70,.52,-.72],'dark','good-return-motor','x');gm.userData.rotor=true;gm.userData.rotorAxis='x';gm.userData.spinDirection=1;const bad=this.group(g,'shark650-return-bad','Rejected-product return belt');for(const z of [.42,.62]){this.box(bad,[1.30,.025,.12],[-.05,.59,z],'rubber',.006);for(const x of [-.54,.54])this.cyl(bad,.05,.14,[x,.58,z],'steel','bad-return','z');}const bm=this.cyl(bad,.09,.22,[-.60,.40,.72],'dark','bad-return-motor','x');bm.userData.rotor=true;bm.userData.rotorAxis='x';bm.userData.spinDirection=1;const stack=this.group(g,'shark650-return-stack','Collection / palletizing interface');this.box(stack,[.70,.08,.88],[.85,.40,-.18],'steel');this.box(stack,[.62,.08,.58],[.72,.32,.62],'steel');stack.userData.verticalPalletizingCapability=true;stack.userData.installedVerticalPalletizerVerified=false;for(const z of [-.18,.62]){const sensor=this.box(stack,[.05,.07,.05],[.48,.66,z],'green',.005);sensor.userData.mechanismRole=z<0?'good-return-confirm-sensor-reference':'bad-return-confirm-sensor-reference';}}
 findNode(id){return id==='shark650-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;let count=0;for(const m of this.meshes)if(m.userData.exteriorCover){m.visible=!on;count++;}this.root.userData.interiorCutawayVisible=!!on;this.root.userData.exteriorHiddenCount=on?count:0;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){const open=this.exteriorOpen;this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);this.setExteriorOpen(open);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
