import * as THREE from 'three';
import {OFFSET9_MODULE_SEQUENCE,OFFSET9_CENTERS} from './data/dimensions-offset9.js';
export const OFFSET9_SIMULATION_STAGES=Object.freeze(['Pile separation','Central suction-belt feeder','Front and side register',...OFFSET9_MODULE_SEQUENCE.map(m=>m.label),'Venturi sheet guide','Sheet brake','Delivery pile']);
export class Offset9PrintingSimulation{
 constructor(root,template){this.root=root;this.template=template;this.active=false;this.running=false;this.speed=1;this.completed=0;this.startAt=0;this.elapsed=0;this.rotors=[];this.nozzles=[];this.sheets=[];this.stack=[];this.inkVisible=true;this.pathVisible=false;root.traverse(o=>{if(o.isMesh&&o.userData.rotor)this.rotors.push(o);if(o.userData.airNozzle)this.nozzles.push(o);});this.points=[[-4.22,1.24,0],[-2.86,1.20,0],...OFFSET9_MODULE_SEQUENCE.map(m=>[OFFSET9_CENTERS[m.key],m.type==='coat'?.94:.88,0]),[3.62,1.10,0],[5.38,.64,0]].map(p=>new THREE.Vector3(...p));this.curve=new THREE.CatmullRomCurve3(this.points,false,'centripetal');const material=new THREE.MeshStandardMaterial({color:0xf4efdc,roughness:.88,side:THREE.DoubleSide});for(let i=0;i<8;i++){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.37,.52),material.clone());mesh.rotation.x=-Math.PI/2;mesh.visible=false;mesh.userData.simSheet=true;root.add(mesh);this.sheets.push({mesh,phase:i/8,lap:-1});}for(let i=0;i<18;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.37,.006,.52),material.clone());mesh.visible=false;root.add(mesh);this.stack.push(mesh);}this.rest=this.rotors.map(o=>o.rotation.z);}
 start(){this.active=this.running=true;this.startAt=performance.now();this.elapsed=0;this.completed=0;return this.state();}pause(){this.running=false;}resume(){if(this.active)this.running=true;}setSpeed(value){this.speed=Math.max(.25,Math.min(4,Number(value)||1));}setPathVisible(value){this.pathVisible=!!value;}setInkFlowVisible(value){this.inkVisible=!!value;}
 update(now){if(!this.active||!this.running)return;this.elapsed=(now-this.startAt)/1000*this.speed;const cycle=12;for(let i=0;i<this.rotors.length;i++)this.rotors[i].rotation.z=this.rest[i]+this.elapsed*(i%2?-6:6);for(const [i,sheet] of this.sheets.entries()){const raw=this.elapsed/cycle+sheet.phase,t=raw%1;sheet.mesh.visible=true;sheet.mesh.position.copy(this.curve.getPointAt(t));sheet.mesh.rotation.y=0;const coatStart=.68;sheet.mesh.material.color.setHex(t>coatStart?0xe8dfc1:0xf4efdc);const lap=Math.floor(raw);if(raw>=1&&lap!==sheet.lap){sheet.lap=lap;this.completed++;const pile=this.stack[(this.completed-1)%this.stack.length];pile.visible=true;pile.position.set(5.38,.49+((this.completed-1)%this.stack.length)*.007,0);}}const point=this.curve.getPointAt((this.elapsed/cycle)%1);for(const nozzle of this.nozzles){const world=new THREE.Vector3();nozzle.getWorldPosition(world);nozzle.material.emissive?.setHex(Math.abs(world.x-point.x)<.42?0x2fabc3:0);nozzle.material.emissiveIntensity=Math.abs(world.x-point.x)<.42?1.4:0;}}
 stop(){this.active=this.running=false;for(const s of this.sheets)s.mesh.visible=false;for(const p of this.stack)p.visible=false;for(const [i,r] of this.rotors.entries())r.rotation.z=this.rest[i];for(const n of this.nozzles){n.material.emissive?.setHex(0);n.material.emissiveIntensity=0;}return this.state();}
 state(){const progress=this.active?(this.elapsed/12)%1:0,index=Math.min(OFFSET9_SIMULATION_STAGES.length-1,Math.floor(progress*OFFSET9_SIMULATION_STAGES.length));return{active:this.active,running:this.running,paused:this.active&&!this.running,speed:this.speed,stage:OFFSET9_SIMULATION_STAGES[index],completed:this.completed,progress,sheetsVisible:this.sheets.filter(s=>s.mesh.visible).length,rotorCount:this.rotors.length,airGuidanceActive:this.nozzles.some(n=>n.material.emissiveIntensity>0),pileSheetsVisible:this.stack.filter(s=>s.visible).length};}
 dispose(){this.stop();for(const s of this.sheets){this.root.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();}for(const p of this.stack){this.root.remove(p);p.geometry.dispose();p.material.dispose();}}
}
