import * as THREE from 'three';
export const MK1060_SIMULATION_STAGES=Object.freeze(['Pile separation','Feed table transfer','Front / side registration','Gripper index to platen','Platen close and die-cut dwell','Index to stripping','Double-action stripping','Index to blanking','Blank separation','Edge-waste / product delivery']);
export class MK1060ProcessSimulation{
 constructor(root,template){this.root=root;this.template=template;this.active=false;this.running=false;this.speed=1;this.completed=0;this.elapsed=0;this.startAt=0;this.rotors=[];this.sheets=[];this.blankStack=[];this.wastePieces=[];this.lower=template.findNode('mk1060-platen-lower');this.stripUpper=template.findNode('mk1060-strip-upper');this.stripLower=template.findNode('mk1060-strip-lower');this.blankUpper=template.findNode('mk1060-blank-upper');this.blankLower=template.findNode('mk1060-blank-lower');this.restY={lower:this.lower?.position.y||0,su:this.stripUpper?.position.y||0,sl:this.stripLower?.position.y||0,bu:this.blankUpper?.position.y||0,bl:this.blankLower?.position.y||0};root.traverse(o=>{if(o.isMesh&&o.userData.rotor)this.rotors.push(o);});this.points=[[-4.36,1.34,0],[-3.35,1.15,0],[-2.60,1.17,0],[-1.35,1.48,0],[.35,1.46,0],[1.95,1.46,0],[3.55,.84,0],[4.10,.78,0]].map(p=>new THREE.Vector3(...p));this.curve=new THREE.CatmullRomCurve3(this.points,false,'centripetal');const mat=new THREE.MeshStandardMaterial({color:0xefe8d3,roughness:.88,side:THREE.DoubleSide});for(let i=0;i<7;i++){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1.02,.72),mat.clone());mesh.rotation.x=-Math.PI/2;mesh.visible=false;root.add(mesh);this.sheets.push({mesh,phase:i/7,lap:-1});}for(let i=0;i<20;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.50,.006,.30),mat.clone());mesh.visible=false;root.add(mesh);this.blankStack.push(mesh);const waste=new THREE.Mesh(new THREE.BoxGeometry(.98,.012,.07),new THREE.MeshStandardMaterial({color:0xb4966d,roughness:.9}));waste.visible=false;root.add(waste);this.wastePieces.push(waste);}this.restRot=this.rotors.map(r=>r.rotation.z);}
 start(){this.active=this.running=true;this.startAt=performance.now();this.elapsed=0;this.completed=0;return this.state();}pause(){this.running=false;}resume(){if(this.active)this.running=true;}setSpeed(v){this.speed=Math.max(.25,Math.min(4,Number(v)||1));}setPathVisible(v){this.pathVisible=!!v;}setInkFlowVisible(){return this.state();}
 update(now){if(!this.active||!this.running)return;this.elapsed=(now-this.startAt)/1000*this.speed;const cycle=11.5,phase=(this.elapsed/cycle)%1,platen=THREE.MathUtils.smoothstep(phase,.31,.37)*(1-THREE.MathUtils.smoothstep(phase,.43,.48)),strip=THREE.MathUtils.smoothstep(phase,.57,.61)*(1-THREE.MathUtils.smoothstep(phase,.67,.71)),blank=THREE.MathUtils.smoothstep(phase,.79,.83)*(1-THREE.MathUtils.smoothstep(phase,.89,.93)),indexing=!(phase>.31&&phase<.48)&&!(phase>.57&&phase<.71)&&!(phase>.79&&phase<.93),waste=phase>.90||phase<.08;
  if(this.lower)this.lower.position.y=this.restY.lower+platen*.25;if(this.stripUpper)this.stripUpper.position.y=this.restY.su-strip*.12;if(this.stripLower)this.stripLower.position.y=this.restY.sl+strip*.10;if(this.blankUpper)this.blankUpper.position.y=this.restY.bu-blank*.14;if(this.blankLower)this.blankLower.position.y=this.restY.bl+blank*.08;
  for(const [i,r] of this.rotors.entries()){const role=String(r.userData.mechanismRole||''),canMove=role.includes('waste')?waste:indexing;if(canMove)r.rotation.z=this.restRot[i]+this.elapsed*(i%2?-3.4:3.4);}
  for(const [i,s] of this.sheets.entries()){const raw=this.elapsed/cycle+s.phase,tRaw=raw%1,t=Math.min(.999,tRaw);s.mesh.visible=true;s.mesh.position.copy(this.curve.getPointAt(t));s.mesh.rotation.y=0;if(t>.52&&t<.72)s.mesh.material.color.setHex(strip>.45?0xd6c29b:0xe9dfc7);else if(t>.72)s.mesh.material.color.setHex(0xdcc79e);else s.mesh.material.color.setHex(0xefe8d3);const lap=Math.floor(raw);if(raw>=1&&lap!==s.lap){s.lap=lap;this.completed++;const idx=(this.completed-1)%this.blankStack.length,b=this.blankStack[idx],w=this.wastePieces[idx];b.visible=true;b.position.set(4.02,.47+idx*.007,-.24);w.visible=true;w.position.set(3.58,.58+idx*.003,.56);}}
  this.phase=phase;this.platenClosed=platen>.82;this.strippingActive=strip>.32;this.blankingActive=blank>.32;this.wasteConveyorActive=waste;
 }
 stop(){this.active=this.running=false;if(this.lower)this.lower.position.y=this.restY.lower;if(this.stripUpper)this.stripUpper.position.y=this.restY.su;if(this.stripLower)this.stripLower.position.y=this.restY.sl;if(this.blankUpper)this.blankUpper.position.y=this.restY.bu;if(this.blankLower)this.blankLower.position.y=this.restY.bl;for(const [i,r] of this.rotors.entries())r.rotation.z=this.restRot[i];for(const s of this.sheets)s.mesh.visible=false;for(const b of this.blankStack)b.visible=false;for(const w of this.wastePieces)w.visible=false;return this.state();}
 state(){const progress=this.active?(this.elapsed/11.5)%1:0,index=Math.min(MK1060_SIMULATION_STAGES.length-1,Math.floor(progress*MK1060_SIMULATION_STAGES.length));return{active:this.active,running:this.running,paused:this.active&&!this.running,speed:this.speed,stage:MK1060_SIMULATION_STAGES[index],completed:this.completed,progress,sheetsVisible:this.sheets.filter(s=>s.mesh.visible).length,mechanismCount:this.rotors.length,platenClosed:!!this.platenClosed,strippingActive:!!this.strippingActive,blankingActive:!!this.blankingActive,wasteConveyorActive:!!this.wasteConveyorActive,pileSheetsVisible:this.blankStack.filter(p=>p.visible).length,wastePiecesVisible:this.wastePieces.filter(p=>p.visible).length};}
 dispose(){this.stop();for(const s of this.sheets){this.root.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();}for(const b of this.blankStack){this.root.remove(b);b.geometry.dispose();b.material.dispose();}for(const w of this.wastePieces){this.root.remove(w);w.geometry.dispose();w.material.dispose();}}
}
