import * as THREE from 'three';
export const MK920_SIMULATION_STAGES=Object.freeze(['Pile separation','Feeder transfer','Front and side registration','Gripper-chain index','Platen close and pressure dwell','Foil transfer / die-cut','Platen open','Foil advance and waste rewind','Gripper release','Delivery pile']);
export class MK920StampingSimulation{
 constructor(root,template){this.root=root;this.template=template;this.active=false;this.running=false;this.speed=1;this.completed=0;this.elapsed=0;this.startAt=0;this.rotors=[];this.heaters=[];this.foilAxes=[];this.sheets=[];this.stack=[];this.lower=template.findNode('mk920-platen-lower');this.lowerRest=this.lower?.position.y||0;root.traverse(o=>{if(o.isMesh&&o.userData.rotor)this.rotors.push(o);if(o.userData.heater)this.heaters.push(o);if(o.userData.foilPullAxis)this.foilAxes.push(o);});this.points=[[-3.34,1.35,0],[-2.33,1.15,0],[-1.42,1.14,0],[-.15,1.46,0],[1.20,1.25,0],[2.98,.68,0]].map(p=>new THREE.Vector3(...p));this.curve=new THREE.CatmullRomCurve3(this.points,false,'centripetal');const mat=new THREE.MeshStandardMaterial({color:0xf1ead7,roughness:.88,side:THREE.DoubleSide});for(let i=0;i<6;i++){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.92,.65),mat.clone());mesh.rotation.x=-Math.PI/2;mesh.visible=false;root.add(mesh);this.sheets.push({mesh,phase:i/6,lap:-1});}for(let i=0;i<16;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.92,.006,.65),mat.clone());mesh.visible=false;root.add(mesh);this.stack.push(mesh);}this.rest=this.rotors.map(r=>r.rotation.z);}
 start(){this.active=this.running=true;this.startAt=performance.now();this.elapsed=0;this.completed=0;return this.state();}pause(){this.running=false;}resume(){if(this.active)this.running=true;}setSpeed(v){this.speed=Math.max(.25,Math.min(4,Number(v)||1));}setPathVisible(v){this.pathVisible=!!v;}setInkFlowVisible(v){this.foilVisible=!!v;}
 update(now){if(!this.active||!this.running)return;this.elapsed=(now-this.startAt)/1000*this.speed;const cycle=10,phase=(this.elapsed/cycle)%1,indexing=phase<.38||phase>.72,close=THREE.MathUtils.smoothstep(phase,.38,.48)*(1-THREE.MathUtils.smoothstep(phase,.64,.72)),dwell=phase>=.48&&phase<=.64,foilAdvance=phase>.72;
  if(this.lower)this.lower.position.y=this.lowerRest+close*.25;for(const h of this.heaters){h.material.emissive?.setHex(dwell?0xff7c28:0x5b1c0b);h.material.emissiveIntensity=dwell?2.2:.35;}
  for(const [i,r] of this.rotors.entries()){const isFoil=r.userData.foilPullAxis||String(r.userData.mechanismRole).includes('foil')||String(r.userData.mechanismRole).includes('rewind');const canMove=isFoil?foilAdvance:indexing;if(canMove)r.rotation.z=this.rest[i]+this.elapsed*(i%2?-3.8:3.8);}
  const motion=indexing?(phase<.38?phase/.38:(phase-.72)/.28):1;for(const [i,s] of this.sheets.entries()){const raw=this.elapsed/cycle+s.phase,tRaw=raw%1,station=Math.floor(tRaw*5),local=tRaw*5-station,t=(station+Math.min(1,motion>0?local:0))/5;s.mesh.visible=true;s.mesh.position.copy(this.curve.getPointAt(Math.min(.999,t)));s.mesh.rotation.y=0;if(dwell&&t>.45&&t<.58)s.mesh.material.color.setHex(0xe1c06a);else if(t>.55)s.mesh.material.color.setHex(0xead9a8);else s.mesh.material.color.setHex(0xf1ead7);const lap=Math.floor(raw);if(raw>=1&&lap!==s.lap){s.lap=lap;this.completed++;const p=this.stack[(this.completed-1)%this.stack.length];p.visible=true;p.position.set(2.98,.47+((this.completed-1)%this.stack.length)*.007,0);}}
  this.phase=phase;this.platenClosed=close>.85;this.pressureDwell=dwell;this.foilAdvancing=foilAdvance;
 }
 stop(){this.active=this.running=false;if(this.lower)this.lower.position.y=this.lowerRest;for(const h of this.heaters){h.material.emissive?.setHex(0);h.material.emissiveIntensity=0;}for(const [i,r] of this.rotors.entries())r.rotation.z=this.rest[i];for(const s of this.sheets)s.mesh.visible=false;for(const p of this.stack)p.visible=false;return this.state();}
 state(){const progress=this.active?(this.elapsed/10)%1:0,index=Math.min(MK920_SIMULATION_STAGES.length-1,Math.floor(progress*MK920_SIMULATION_STAGES.length));return{active:this.active,running:this.running,paused:this.active&&!this.running,speed:this.speed,stage:MK920_SIMULATION_STAGES[index],completed:this.completed,progress,sheetsVisible:this.sheets.filter(s=>s.mesh.visible).length,mechanismCount:this.rotors.length,platenClosed:!!this.platenClosed,pressureDwell:!!this.pressureDwell,foilAdvancing:!!this.foilAdvancing,foilAxisCount:this.foilAxes.length,pileSheetsVisible:this.stack.filter(p=>p.visible).length};}
 dispose(){this.stop();for(const s of this.sheets){this.root.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();}for(const p of this.stack){this.root.remove(p);p.geometry.dispose();p.material.dispose();}}
}
