import * as THREE from 'three';
export const FZ1200_SIMULATION_STAGES=Object.freeze(['Load pile','Clamp pile','Lift to turning clearance','Turn pile 180°','Air separation / dust removal','Jog / align','Stabilize turned pile','Lower for unloading']);
export class FZ1200ProcessSimulation{
 constructor(root,template){this.root=root;this.template=template;this.active=false;this.running=false;this.speed=1;this.elapsed=0;this.startAt=0;this.completed=0;this.clamp=template.findNode('fz1200-clamp');this.upper=template.findNode('fz1200-clamp-upper');this.yoke=template.findNode('fz1200-turn-yoke');this.pile=template.findNode('fz1200-pile');this.side=template.findNode('fz1200-jog-side');this.front=template.findNode('fz1200-jog-front');this.rotors=[];this.nozzles=[];root.traverse(o=>{if(o.isMesh&&o.userData.rotor)this.rotors.push(o);if(o.isMesh&&o.userData.airNozzle)this.nozzles.push(o);});this.rest={upperY:this.upper?.position.y||0,clampRot:this.clamp?.rotation.z||0,yokeRot:this.yoke?.rotation.z||0,pileY:this.pile?.position.y||0,sideX:this.side?.position.x||0,frontZ:this.front?.position.z||0};this.restRot=this.rotors.map(r=>r.rotation.z);}
 start(){this.active=this.running=true;this.startAt=performance.now();this.elapsed=0;this.completed=0;return this.state();}pause(){this.running=false;}resume(){if(this.active)this.running=true;}setSpeed(v){this.speed=Math.max(.25,Math.min(3,Number(v)||1));}setPathVisible(){}setInkFlowVisible(){}
 update(now){if(!this.active||!this.running)return;this.elapsed=(now-this.startAt)/1000*this.speed;const cycle=12,phase=(this.elapsed/cycle)%1,clamp=THREE.MathUtils.smoothstep(phase,.10,.20),lift=THREE.MathUtils.smoothstep(phase,.20,.30)*(1-THREE.MathUtils.smoothstep(phase,.82,.94)),turn=THREE.MathUtils.smoothstep(phase,.30,.47),air=phase>.48&&phase<.67,jog=phase>.58&&phase<.75;
  if(this.upper)this.upper.position.y=this.rest.upperY-clamp*.54;if(this.clamp)this.clamp.rotation.z=this.rest.clampRot+turn*Math.PI;if(this.yoke)this.yoke.rotation.z=this.rest.yokeRot;if(this.pile)this.pile.position.y=this.rest.pileY+lift*.18;
  if(this.side)this.side.position.x=this.rest.sideX+(jog?Math.sin(this.elapsed*24)*.018:0);if(this.front)this.front.position.z=this.rest.frontZ+(jog?Math.sin(this.elapsed*21)*.018:0);
  for(const [i,r] of this.rotors.entries()){const role=String(r.userData.mechanismRole||''),move=role.includes('blower')?air:role.includes('vibration')?jog:role.includes('rotation')||role.includes('trunnion')?phase>.28&&phase<.50:false;if(move)r.rotation.z=this.restRot[i]+this.elapsed*(i%2?-3.2:3.2);}
  this.phase=phase;this.clamped=clamp>.9;this.turnAngleDeg=turn*180;this.airingActive=air;this.joggingActive=jog;if(phase>.96&&!this.counted){this.completed++;this.counted=true;}if(phase<.05)this.counted=false;
 }
 stop(){this.active=this.running=false;if(this.upper)this.upper.position.y=this.rest.upperY;if(this.clamp)this.clamp.rotation.z=this.rest.clampRot;if(this.yoke)this.yoke.rotation.z=this.rest.yokeRot;if(this.pile)this.pile.position.y=this.rest.pileY;if(this.side)this.side.position.x=this.rest.sideX;if(this.front)this.front.position.z=this.rest.frontZ;for(const [i,r] of this.rotors.entries())r.rotation.z=this.restRot[i];return this.state();}
 state(){const progress=this.active?(this.elapsed/12)%1:0,index=Math.min(FZ1200_SIMULATION_STAGES.length-1,Math.floor(progress*FZ1200_SIMULATION_STAGES.length));return{active:this.active,running:this.running,paused:this.active&&!this.running,speed:this.speed,stage:FZ1200_SIMULATION_STAGES[index],completed:this.completed,progress,mechanismCount:this.rotors.length,clamped:!!this.clamped,turnAngleDeg:this.turnAngleDeg||0,airingActive:!!this.airingActive,joggingActive:!!this.joggingActive,sheetsVisible:1,pileSheetsVisible:1};}
 dispose(){this.stop();}
}
