import * as THREE from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {UPG_LY300_SPEC} from './data/dimensions-upg-ly300.js';import {UPG_LY300_TAXONOMY,UPG_LY300_TAXONOMY_BY_ID} from './data/taxonomy-upg-ly300.js';import {UPG_LY300_ORIENTATION,UPG_LY300_TECHNICAL_SOURCES} from './data/sources-upg-ly300.js';import {V141_SOURCE_STATS} from './data/research-v141.js';
const V=a=>new THREE.Vector3(...a);
export class UpgLy300MachineTemplate{
 constructor(){this.spec=UPG_LY300_SPEC;this.root=new THREE.Group();this.root.name='DIGITAL INKJET · UPG-LY300';this.root.userData={assetId:this.spec.assetId,nodeId:'ly300-root',spec:this.spec,sources:UPG_LY300_TECHNICAL_SOURCES,orientation:UPG_LY300_ORIENTATION,taxonomyVersion:'ly300-v3-print-cure-inspection-interlock',detailPass:'V141_LY300_POSITION_PRINT_CURE_INSPECT_REJECT',researchVersion:'V141',researchSourceCount:V141_SOURCE_STATS.total,uniqueResearchUrls:V141_SOURCE_STATS.uniqueUrls,evidenceGrade:'OEM_MODEL_GROUNDED',geometryStatus:'OEM_MODEL_PROCESS_REFERENCE__ACCESSORIES_BOUNDED',engineeringDimensions:false};this.parts=[];this.nodes=[];this.meshes=[];this.geometries=new Map();this.materials=new Map();this.build();this.taxonomy=UPG_LY300_TAXONOMY;this.taxonomyById=UPG_LY300_TAXONOMY_BY_ID;for(const n of this.nodes){n.userData.rest=n.position.clone();n.userData.restQuaternion=n.quaternion.clone();}this.root.updateMatrixWorld(true);}
 group(parent,id,name,pos=[0,0,0],explode=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);g.userData={assetId:this.spec.assetId,nodeId:id,selectable:true,explode:V(explode),confidence:'OEM_MODEL_GROUNDED'};parent.add(g);this.nodes.push(g);if(parent===this.root)this.parts.push(g);return g;}
 mat(k){if(!this.materials.has(k)){const c={charcoal:0x282b2d,dark:0x161b1e,black:0x090c0e,steel:0x879196,silver:0xc0c7c9,blue:0x387eab,cyan:0x4ea6bd,red:0xb33b34,green:0x57916f,amber:0xd5a54a,paper:0xe0cba2,ink:0x17191a,glass:0x4a6973,uv:0xdce7ff}[k]||0x888888;const m=new THREE.MeshStandardMaterial({color:c,metalness:['steel','silver'].includes(k)?.5:.10,roughness:k==='glass'?.18:.43,transparent:k==='glass',opacity:k==='glass'?.38:1});m.userData.baseOpacity=m.opacity;this.materials.set(k,m);}return this.materials.get(k);}
 mesh(g,geo,key,k='charcoal',p=[0,0,0],r=null){if(!this.geometries.has(key))this.geometries.set(key,geo());const m=new THREE.Mesh(this.geometries.get(key),this.mat(k));m.position.set(...p);if(r)m.rotation.set(...r);m.castShadow=k!=='glass';m.receiveShadow=true;m.userData.ownerId=g.userData.nodeId;g.add(m);this.meshes.push(m);return m;}
 box(g,s,p,k='charcoal',rad=.02){return this.mesh(g,()=>rad?new RoundedBoxGeometry(...s,2,rad):new THREE.BoxGeometry(...s),'b'+s+rad,k,p);}
 cyl(g,r,l,p,k='steel',role='',axis='z'){
  const rot=axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:null,m=this.mesh(g,()=>new THREE.CylinderGeometry(r,r,l,22),'c'+r+l+axis,k,p,rot);
  const rotating=/^(pager-wheel|belt-pulley|servo|encoder|negative-pump)$/.test(role);
  m.userData.rotor=rotating;m.userData.mechanismRole=role;m.userData.rotorAxis=axis;m.userData.radius=r;
  if(rotating)m.userData.spinDirection=/^(belt-pulley|encoder)$/.test(role)?-1:1;
  return m;
 }cover(m){m.userData.exteriorCover=true;return m;}
 build(){this.buildAccess();this.buildFeeder();this.buildTransport();this.buildPrint();this.buildInk();this.buildUV();this.buildCamera();this.buildReject();this.buildCollect();this.buildControl();}
 buildAccess(){const g=this.group(this.root,'ly300-access','Enclosure and service access');const frame=this.group(g,'ly300-access-frame','4230 mm machine base reference');this.box(frame,[4.23,.22,.72],[0,.11,0],'dark',.025);for(const x of [-1.72,-.75,.25,1.22,1.88])for(const z of [-.31,.31])this.box(frame,[.06,.65,.06],[x,.46,z],'steel',.01);const cover=this.group(g,'ly300-access-cover','Service enclosure panels');for(const z of [-.37,.37])for(const [x,w,h] of [[-.65,1.10,1.18],[.55,.95,1.18],[1.38,.62,.90]])this.cover(this.box(cover,[w,h,.04],[x,.84+h/2,z],'charcoal',.035));const door=this.group(g,'ly300-access-door','Service doors / ventilation');for(const x of [-.92,-.38,.35,.82,1.38]){this.box(door,[.42,.48,.018],[x,.55,-.395],'dark',.018);for(let y=.38;y<.68;y+=.075)this.box(door,[.22,.012,.012],[x,y,-.408],'steel',0);}}
 buildFeeder(){const g=this.group(this.root,'ly300-feeder','Automatic paging / feeding',[-1.72,0,0],[-.45,.12,0]);const stack=this.group(g,'ly300-feed-stack','Input pile support');this.box(stack,[.72,.07,.50],[-.10,.39,0],'steel');for(let i=0;i<9;i++)this.box(stack,[.44,.009,.23],[-.14,.47+i*.011,0],'paper',.002);const baffle=this.group(g,'ly300-feed-baffle','Baffle feeder');for(const z of [-.14,.14])this.box(baffle,[.10,.45,.035],[-.28,.74,z],'steel',.008);const pager=this.group(g,'ly300-feed-pager','Automatic paging mechanism');for(const z of [-.16,0,.16]){this.cyl(pager,.04,.08,[.24,.65,z],'rubber','pager-wheel','z');this.box(pager,[.44,.024,.065],[.16,.59,z],'black',.004);}const fm=this.cyl(pager,.085,.20,[-.08,.48,.28],'dark','feeder-vfd-motor','x');fm.userData.rotor=true;fm.userData.rotorAxis='x';fm.userData.spinDirection=1;const dbl=this.group(g,'ly300-feed-double','Double-sheet sensing zone');for(const z of [-.13,.13]){const sensor=this.box(dbl,[.06,.14,.07],[.39,.88,z],'cyan',.012);sensor.userData.mechanismRole=z<0?'feed-presence-sensor-reference':'double-sheet-sensor-reference';}}
 buildTransport(){const g=this.group(this.root,'ly300-transport','Servo transport and positioning',[-.72,0,0],[-.22,.12,0]);const belt=this.group(g,'ly300-transport-belt','High-temperature PU conveyor belt');this.box(belt,[2.20,.035,.52],[0,.60,0],'black',.008);for(const x of [-.98,.98])this.cyl(belt,.07,.55,[x,.59,0],'steel','belt-pulley','z');const servo=this.group(g,'ly300-transport-servo','Servo transport drive');this.cyl(servo,.12,.34,[-.86,.36,.34],'dark','servo','x');const coupling=this.cyl(servo,.045,.10,[-.66,.36,.34],'amber','servo-coupling','x');coupling.userData.mechanismRole='servo-coupling';const enc=this.group(g,'ly300-transport-encoder','Encoder / positioning reference');this.cyl(enc,.045,.08,[-.68,.72,.29],'cyan','encoder','z');const trigger=this.group(g,'ly300-transport-trigger','Print trigger / position confirmation');for(const z of [-.14,.14]){const p=this.box(trigger,[.045,.070,.045],[-.38,.78,z],z<0?'cyan':'green',.004);p.userData.mechanismRole=z<0?'print-trigger-emitter':'print-trigger-receiver';}}
 buildPrint(){const g=this.group(this.root,'ly300-print','UV piezo print system',[-.18,0,0],[0,.30,.30]);const head=this.group(g,'ly300-print-head','Ricoh G5 printhead module reference');head.userData.installedPrintheadCountVerified=false;this.box(head,[.43,.15,.20],[0,1.03,0],'dark',.025);head.userData.printHead=true;const nozzle=this.group(g,'ly300-print-nozzle','Nozzle / jetting interface');const n=this.box(nozzle,[.34,.018,.10],[0,.92,0],'ink',.004);n.userData.nozzleArray=true;const height=this.group(g,'ly300-print-height','Printhead mounting / height interface');for(const z of [-.16,.16]){this.box(height,[.06,.55,.06],[-.17,.94,z],'steel',.008);this.box(height,[.46,.05,.05],[0,1.25,z],'steel',.008);const screw=this.cyl(height,.018,.34,[-.17,1.04,z],'steel','printhead-height-screw','y');screw.userData.mechanismRole='printhead-height-screw';}const interlock=this.box(height,[.045,.060,.045],[.18,.92,.16],'green',.004);interlock.userData.mechanismRole='printhead-height-position-sensor-reference';}
 buildInk(){const g=this.group(this.root,'ly300-ink','Ink / negative-pressure system',[.15,0,0],[0,.22,.38]);const tank=this.group(g,'ly300-ink-tank','UV ink reservoir');this.box(tank,[.32,.48,.28],[.05,.50,.31],'black',.04);const neg=this.group(g,'ly300-ink-negative','Negative-pressure system');this.box(neg,[.24,.30,.24],[.40,.55,.30],'dark',.035);this.cyl(neg,.055,.18,[.40,.78,.30],'steel','negative-pump','x');const gauge=this.cyl(neg,.050,.025,[.56,.68,.30],'glass','negative-pressure-gauge','z');gauge.userData.mechanismRole='negative-pressure-gauge';const sensor=this.box(neg,[.050,.070,.045],[.56,.50,.30],'cyan',.004);sensor.userData.mechanismRole='negative-pressure-ready-sensor-reference';const filter=this.cyl(neg,.040,.16,[.25,.48,.46],'steel','ink-filter-reference','y');filter.userData.mechanismRole='ink-filter-reference';const tube=this.group(g,'ly300-ink-tube','Ink tube / connector routing');for(const z of [-.05,.05])this.cyl(tube,.010,.76,[.12,.82,z],'ink','ink-line','y');}
 buildUV(){const g=this.group(this.root,'ly300-uv','LED UV curing',[.48,0,0],[0,.30,-.30]);const led=this.group(g,'ly300-uv-led','LED UV curing head');const lamp=this.box(led,[.28,.14,.42],[0,.95,0],'uv',.018);lamp.userData.uvLamp=true;lamp.material=lamp.material.clone();lamp.material.userData.baseOpacity=1;const shield=this.group(g,'ly300-uv-shield','UV lamp shield');this.cover(this.box(shield,[.38,.36,.52],[0,.98,0],'charcoal',.035));const interlock=this.box(shield,[.045,.060,.045],[.16,.82,-.24],'green',.004);interlock.userData.mechanismRole='uv-shield-interlock-sensor-reference';const power=this.group(g,'ly300-uv-power','UV power interface');this.box(power,[.28,.34,.26],[.05,.49,.30],'blue',.03);const ready=this.box(power,[.055,.070,.045],[.16,.68,.29],'cyan',.004);ready.userData.mechanismRole='uv-power-ready-sensor-reference';}
 buildCamera(){const g=this.group(this.root,'ly300-camera','2K camera inspection',[.95,0,0],[.18,.28,.30]);const line=this.group(g,'ly300-camera-line','2K line-scan camera');this.box(line,[.18,.28,.20],[0,1.08,0],'dark',.025);this.cyl(line,.045,.08,[0,.91,0],'black','camera-lens','z');const trig=this.box(line,[.045,.065,.045],[-.18,.82,-.16],'cyan',.004);trig.userData.mechanismRole='camera-trigger-sensor-reference';const light=this.group(g,'ly300-camera-light','Inspection illumination');for(const z of [-.16,.16]){const l=this.box(light,[.34,.025,.055],[0,.83,z],'uv',.006);l.userData.inspectionLight=true;l.material=l.material.clone();l.material.userData.baseOpacity=1;}const trace=this.group(g,'ly300-camera-trace','Detection / traceability interface');this.box(trace,[.22,.17,.16],[.28,.75,.29],'cyan',.02);}
 buildReject(){const g=this.group(this.root,'ly300-reject','Plate-turn reject',[1.34,0,0],[.35,.16,0]);const plate=this.group(g,'ly300-reject-plate','Plate-turn reject actuator');const p=this.box(plate,[.08,.28,.42],[0,.76,0],'red',.015);p.userData.rejectPlate=true;const cyl=this.group(g,'ly300-reject-cylinder','Air-cylinder actuation');this.cyl(cyl,.04,.28,[-.20,.62,.28],'steel','reject-cylinder','x');const sol=this.box(cyl,[.12,.11,.10],[-.34,.49,.28],'blue',.009);sol.userData.mechanismRole='reject-solenoid-valve-reference';const home=this.box(cyl,[.045,.060,.045],[-.06,.78,.24],'green',.004);home.userData.mechanismRole='reject-home-sensor-reference';const bin=this.group(g,'ly300-reject-bin','Rejected-product path');this.box(bin,[.42,.08,.30],[.25,.37,.34],'steel',.018);const conf=this.box(bin,[.045,.060,.045],[.36,.58,.32],'cyan',.004);conf.userData.mechanismRole='reject-confirm-sensor-reference';}
 buildCollect(){const g=this.group(this.root,'ly300-collect','Collection / strapping interface',[1.78,0,0],[.45,.12,0]);const stack=this.group(g,'ly300-collect-stack','Output collection');this.box(stack,[.62,.07,.50],[0,.38,0],'steel');const sensor=this.box(stack,[.045,.060,.045],[.22,.58,-.20],'green',.004);sensor.userData.mechanismRole='collection-output-sensor-reference';const align=this.group(g,'ly300-collect-align','Collection alignment');for(const z of [-.24,.24])this.box(align,[.72,.22,.035],[0,.55,z],'steel',.008);const strap=this.group(g,'ly300-collect-strap','Strapping-machine interface reference');strap.userData.installedStrapperVerified=false;this.box(strap,[.44,.50,.06],[.35,.73,0],'amber',.02);this.box(strap,[.06,.50,.45],[.35,.73,0],'amber',.02);}
 buildControl(){const g=this.group(this.root,'ly300-control','PLC / servo electrical control',[.50,0,0],[0,.16,.45]);const plc=this.group(g,'ly300-control-plc','PLC control cabinet');this.box(plc,[.55,.92,.44],[.10,.74,-.37],'charcoal',.04);const hmi=this.group(g,'ly300-control-hmi','Touchscreen / industrial-PC interface');this.box(hmi,[.38,.28,.025],[-.08,1.04,-.60],'glass',.025);const drive=this.group(g,'ly300-control-drive','Servo and VFD drive electronics');for(const x of [.02,.18,.34])this.box(drive,[.11,.24,.16],[x,.55,-.61],'blue',.018);}
 findNode(id){return id==='ly300-root'?this.root:this.nodes.find(n=>n.userData.nodeId===id)||null;}resolvePart(o){for(let p=o;p&&p!==this.root;p=p.parent)if(p.userData?.selectable)return p;return null;}resolveTaxonomyNode(id){return this.taxonomyById.get(id)?.meshRefs.map(ref=>this.findNode(ref)).find(Boolean)||null;}contains(a,b){for(let p=b;p;p=p.parent)if(p===a)return true;return false;}
 highlight(p){for(const m of this.meshes){m.material.emissive?.setHex(p&&this.contains(p,m)?0x17494a:0);m.material.emissiveIntensity=.3;}}highlightMany(ps=[]){for(const m of this.meshes){m.material.emissive?.setHex(ps.some(p=>this.contains(p,m))?0x17494a:0);m.material.emissiveIntensity=.3;}}ghost(on,except=null){this.ghosted=!!on;for(const m of this.meshes){const fade=on&&(!except||!this.contains(except,m)),natural=m.material.userData?.baseOpacity??1;m.material.transparent=fade||natural<1;m.material.opacity=fade?.14:natural;m.material.depthWrite=!fade;}}isolate(p,on=true){for(const n of this.nodes)n.visible=!on||!p||this.contains(p,n)||this.contains(n,p);}showOnly(ps=[],on=true){for(const n of this.nodes)n.visible=!on||!ps.length||ps.some(p=>n===p||this.contains(n,p));}
 setExteriorOpen(on=true){this.exteriorOpen=!!on;let count=0;for(const m of this.meshes)if(m.userData.exteriorCover){m.visible=!on;count++;}this.root.userData.interiorCutawayVisible=!!on;this.root.userData.exteriorHiddenCount=on?count:0;}explode(t,s=null){for(const n of this.nodes)n.position.copy(n.userData.rest);const targets=s?(s.children.filter(c=>c.userData.selectable).length?s.children.filter(c=>c.userData.selectable):[s]):this.parts;for(const n of targets)n.position.addScaledVector(n.userData.explode,THREE.MathUtils.clamp(+t||0,0,1));}setLow(){}reset(){const open=this.exteriorOpen;this.explode(0);this.highlight(null);this.isolate(null,false);this.ghost(false);for(const n of this.nodes)n.quaternion.copy(n.userData.restQuaternion);this.setExteriorOpen(open);}dispose(){for(const g of this.geometries.values())g.dispose();for(const m of this.materials.values())m.dispose();}
}
