"""Extract 250804 source XY; keep elevation assumptions explicit."""
import ezdxf,json,math,gzip,base64,sys
from pathlib import Path
src=Path(sys.argv[1]);doc=ezdxf.readfile(src);m=doc.modelspace();ox,oy=3708.056953994296,6158.052460509728
pt=lambda p:[round((p[0]-ox)*.01,4),round((p[1]-oy)*.01,4)]
segments=[];axis=[];labels=[];columns=[]
for e in m:
 typ=e.dxftype()
 if typ in ('TEXT','MTEXT'):
  t=(e.dxf.text if typ=='TEXT' else e.plain_text()).strip();x,y=pt(e.dxf.insert)
  if -6<x<99 and 0<y<121 and len(t)>2 and not t.replace(' ','').isdigit():labels.append(dict(text=t,x=x,y=y,handle=e.dxf.handle))
 if typ=='LWPOLYLINE':
  p=list(e.get_points('xy'));p+=p[:1] if e.closed else []
 elif typ=='LINE':p=[tuple(e.dxf.start)[:2],tuple(e.dxf.end)[:2]]
 else:continue
 for a,b in zip(p,p[1:]):
  a,b=pt(a),pt(b)
  if not all(-6.5<=v[0]<=98 and 0<=v[1]<=120 for v in (a,b)):continue
  if math.dist(a,b)<.015:continue
  segments.append([*a,*b])
  if e.dxf.color==18 and math.dist(a,b)>.6 and (abs(a[0]-b[0])<.003 or abs(a[1]-b[1])<.003):
   v=abs(a[0]-b[0])<.003;c=a[0] if v else a[1];lo,hi=sorted([a[1] if v else a[0],b[1] if v else b[0]])
   axis.append((v,c,lo,hi,e.dxf.handle))
walls=[];seen=set()
for i,(v,c,lo,hi,h) in enumerate(axis):
 for vv,cc,ll,hh,h2 in axis[i+1:]:
  sep=abs(c-cc)
  if v!=vv or not .10<sep<.21 or min(hi,hh)-max(lo,ll)<.65 or abs(lo-ll)>.25 or abs(hi-hh)>.25:continue
  center=(c+cc)/2;start=max(lo,ll);end=min(hi,hh);k=(v,round(center/.12),round(start/.2),round(end/.2))
  if k in seen:continue
  seen.add(k);a=[center,start] if v else [start,center];b=[center,end] if v else [end,center]
  walls.append(dict(a=a,b=b,width=round(sep,3),handles=[h,h2],status='DXF_PAIRED_EDGES'))
legacy=[];active=[]
for w in walls:
 a,b=w['a'],w['b']
 if max(a[0],b[0])>34.7 and min(a[0],b[0])<63.1 and max(a[1],b[1])>56.9 and min(a[1],b[1])<65.1:legacy.append(w)
 else:active.append(w)
curtains=[dict(x=x,y=y,width=w,rotation=r,evidence=e) for x,y,w,r,e in [(44.5,86.9,2.4,0,'DXF IN/OUT'),(67.4,86.9,2.8,0,'DXF IN/OUT'),(40,46.2,2.8,0,'DXF IN/OUT'),(65.1,46.2,2.8,0,'DXF IN/OUT'),(38.9,74.2,2.6,0,'DXF OPENING'),(64.2,74.2,2.6,0,'DXF OPENING'),(35.2,60.8,3,90,'USER REQUEST / REVISED ACCESS'),(76.4,58.9,3,90,'USER REQUEST / REVISED ACCESS')]]
doors=[]
for i,w in enumerate(active):
 a,b=w['a'],w['b'];v=abs(a[0]-b[0])<.01;c=a[0] if v else a[1];lo,hi=sorted([a[1] if v else a[0],b[1] if v else b[0]])
 for w2 in active[i+1:]:
  aa,bb=w2['a'],w2['b'];vv=abs(aa[0]-bb[0])<.01;cc=aa[0] if vv else aa[1];ll,hh=sorted([aa[1] if vv else aa[0],bb[1] if vv else bb[0]]);gap=max(ll-hi,lo-hh)
  if v==vv and abs(c-cc)<.04 and .7<gap<1.3:
   t=(hi+ll)/2 if ll>hi else (hh+lo)/2;x,y=(c,t) if v else (t,c)
   if not any(math.hypot(x-d['x'],y-d['y'])<.3 for d in doors):doors.append(dict(x=x,y=y,width=gap,rotation=90 if v else 0,evidence='DXF GAP / LEAF ASSUMED'))
for x in [6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96]:
 for y in [6,30,54,96]:
  if y in [6,96] or x in [6,36,72,96]:columns.append([x,y])
data=dict(baselineId='BMJ-250804-RED-20260921',source=dict(file=src.name,entityCount=len(m),units=doc.units,scale=.01,originX=ox,originY=oy),bounds=dict(minX=-6,minY=0,maxX=98,maxY=120),segments=segments,walls=active,legacyWalls=legacy,labels=labels,doors=doors,curtains=curtains,columns=columns,assumptions={'wallHeight':3.2,'roofEaves':6.8,'roofRidge':8.8,'columnPositions':'GRID_ALIGNED_VISUALIZATION','landscape':'VISUALIZATION_NOT_SURVEYED','doors':'SOURCE_GAP_WITH_ASSUMED_LEAF','roof':'PLAN_FOOTPRINT_WITH_ASSUMED_ELEVATION'})
enc=base64.b64encode(gzip.compress(json.dumps(data,separators=(',',':')).encode())).decode()
Path('frontend/src/data/plant-actual-data.js').write_text("// Generated by scripts/extract-actual-plant.py; CAD XY source, explicit elevation assumptions.\nexport const ACTUAL_PLANT_GZIP='"+enc+"';\n")
Path('../sources/actual-extraction.json').write_text(json.dumps(data));print(dict(segments=len(segments),walls=len(active),legacy=len(legacy),doors=len(doors),labels=len(labels),compressedBytes=len(enc)))
